### ISSUE TITLE
Use subfolder defined by: entire collection path

### ISSUE THREAD

**Issue by orschiro** [jlegewie/zotfile#124]
One request before I will move my entire attachments from Zotero managed folders to a custom folder. 

Is it possible to define the subfolder by the entire collection path of an item?

```
Example:

Item Type: Book
Title: A personal book
```

The item is stored in `My library -> folder A -> subfolder B`.

I know I can use `/%t` so that the subfolder becomes `A personal book`.

However, with thousands of attachments I won't be able to determine anymore to which  item this attachment belongs.

Thus my suggestion: Is it possible to define the subfolder to become `A personal book` within a folder `subfolder B` which is in a folder `folder A`.

This would then reflect the entire collection path and would enhance the structure of the custom folder a lot.

Thanks!

**Comment by jlegewie** [comment]
I am closing because I think this feature is working with `%c` and a popup that asks for the correct folder. Post if it is not working.
