### ISSUE TITLE
possibility to use jotta and other cloud services different than dropbox

### ISSUE THREAD

**Issue by massimom** [jlegewie/zotfile#165]

**Comment by jlegewie** [comment]
zotfile isn't tied to any specific cloud service. As long as there is a folder that get's sync (such as `~/Dropbox`) you are good to go...

**Comment by massimom** [comment]
Hi,

Thanks. I’d like to use a folder in a remote server that doesn’t sync with a daemon. Can I point zotfile to a “backup” folder in the cloud?
I guess I have to combine a relative path to indicate where to go

Or should I use WebDAV for doing things like this

Thanks for your help

cheers
