### ISSUE TITLE
extract annotations from command line?

### ISSUE THREAD

**Issue by titaniumbones** [jlegewie/zotfile#167]
Is it possible to access zotfile from the command line, extract annotations from a pdf, and write those annotations either to a text file or to standard out? If it's possible and htere is an explanation somewhere of how to do it, I would be grateful.  Thanks,
Matt

**Comment by jlegewie** [comment]
Note for the pdf.js based extraction. You can, however, use [my pdf.js fork](https://github.com/jlegewie/pdf.js/tree/extract-v4.2) to extract annotations from the browser. Maybe it's also possible to integrate that in some other setup.

The poppler-based extraction relies on a command line tool. The tool is only complied for mac systems though. Linux should be possible, windows much more complicated. I haven't worked on the popper-based tool for a long time though.

**Comment by titaniumbones** [comment]
Thanks. Looking very quickly at your cod, I wonder it it would be
possible to just access the notes directly via something like zotxt (
https://bitbucket.org/egh/zotxt ), which I believe has access to the
whole Zotero object.  I'm not sure how that would be done but I will try
to look into it soon.

**Comment by jlegewie** [comment]
There is also a python library to access the zotero database. That is, of course, very different than a command line tool...
