### ISSUE TITLE
Renaming rule without blanks

### ISSUE THREAD

**Issue by orschiro** [jlegewie/zotfile#168]
Hi there,

I would like my files to be renamed as follows:

```
authorNameThisIsTheTitleWithoutBlanks2015.pdf
```

I cannot seem to achieve this:

![image](https://cloud.githubusercontent.com/assets/170947/6056738/990075b6-ad15-11e4-93ae-2869e951e0a3.png)

Any ideas on this?

Thankfully,

Robert

**Comment by jlegewie** [comment]
Take a look at user-defined wildcards:
http://zotfile.com/#user-defined-wildcards
That might work for you. Be careful though, it's an advanced feature and you can easily make a mistake that leads to an error message whenever you rename files.

**Comment by orschiro** [comment]
@jlegewie 

Thank you! I will have a look at it.
