### ISSUE TITLE
in duplicate filenames, dots cause early truncation

### ISSUE THREAD

**Issue by lucisandor** [jlegewie/zotfile#171]
I am working with two NEJM, written by the same author, in consecutive issues (same year), carrying the same title. Zotfile is set to move filenames in the same folder and to apply the custom filename `%t{ (%y)}{ (%a)}{ (%s)}`. The first file gets the name `Hypertrichosis (1965) (Forbes) (N. Engl. J. Med.).pdf` as expected. The second gets the name `Hypertrichosis (1965) (Forbes) (N2.pdf`, which truncates early the expected filename.

**Comment by Unode** [comment]
This should have been fixed in https://github.com/jlegewie/zotfile/commit/3effedb0883f91af14b21b010e6d62d2f7ffb397 but there was a typo on the commit message and #117 was referenced instead. Feel free to close.
