### ISSUE TITLE
Zotfile on ipad - Safari

### ISSUE THREAD

**Issue by MSAXB** [jlegewie/zotfile#172]
Hi there
I have set up Zotero folders with all my PhD documents in there.  I am trying to use Goodnotes to annotate the docs using my iPad Air. Zotero allows me to open the docs to Goodnotes but then I cant get the annotated versions back in.  I have tried to download the zotfile plugin....except that Firefox is not available for the iPad yet (unlike on Android devices) so I can't download the plugin.  I am stuck with Safari.  Is there a compatible zotfile plugin for Safari use? Thanks so much, Sarah

**Comment by jlegewie** [comment]
Please use the Zotero forum for support questions: https://forums.zotero.org/discussion/5301/24/zotfile-zotero-plugin-to-rename-move-and-attach-pdfs-send-them-to-ipad-extract-pdf-annotations/
