### ISSUE TITLE
Replacement for punctuation marks of the title

### ISSUE THREAD

**Issue by aoyulong** [jlegewie/zotfile#174]
In the renaming rules of the plugin, there exists one option for truncating punctuation marks.
![qq 20150331103721](https://cloud.githubusercontent.com/assets/3069790/6911366/40d0e4d2-d792-11e4-9412-f2c9c20343fc.png)
When I check it, the title is too short if it has **. : ?**.
![qq20150331104724](https://cloud.githubusercontent.com/assets/3069790/6911453/82ad174e-d793-11e4-89b3-fc3e72cd07e2.png)

When I don't check it, the punctuation marks are replaced with **-**. 
![qq 20150331103618](https://cloud.githubusercontent.com/assets/3069790/6911406/eb41aa1e-d792-11e4-93e8-c95ca7eb878f.png)

In my opinion, I think it's just OK to ignore the punctuation marks and replace them with nothing which is equivalent to delete them.

**Comment by jlegewie** [comment]
Colons and same other characters are not allows in windows filesnames. That is why zotfile replaces them. Here is a list of the characters that are not allows: https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx#naming_conventions

Of course, zotfile could not replace these characters on unix systems and I will keep the issue open for that. It's nothing big but I am still not sure when I will get to that.

**Comment by jlegewie** [comment]
Decided to keep this behavior consistent between windows and mac so closing the issue
