### ISSUE TITLE
Send to tablet fails if attached files have not been renamed yet

### ISSUE THREAD

**Issue by Unode** [jlegewie/zotfile#178]
Sending a file to tablet that has a name other than what Zotfile expects fails on the first try.
The file is renamed but not copied. Once the file is correctly renamed, then everything works as expected.

Versions:
Zotero 4.0.26.3
Zotfile 4.1.3
Firefox 36.0

Steps to reproduce:
1 - Add a zotero entry containing one attached PDF.
2 - Right-click the PDF and pick the "Rename File from Parent Metadata" option included in native Zotero.
3 - Click on the article and select "Manage Attachments > Send to Tablet"
(The error should show up. When clicking on the pop-up as instructed clipboard contains only `{}`)
4 - Repeat step 3.
(Should no longer show an error and the file is copied successfully)

Settings in use:
* Create subfolders from zotero collections
* Rename files when they are sent to the tablet
* Automatically extract annotations when getting PDFs back from tablet
* Renaming rules:
  * Format: {%a-}{%y-}{%s-}{%t-}
  * Replace blanks
  * Maximum length of title: 80
  * Maximum number of authors: 2
  * Add suffix when authors are omitted: _et.al

**Comment by jlegewie** [comment]
Thanks for the report. This should be fixed now. Can you check with the github version?

**Comment by Unode** [comment]
Confirmed as fixed.
