### ISSUE TITLE
Organizing items into CollectionPath(using wildcard %c) - inconsistent between OS

### ISSUE THREAD

**Issue by cmf84** [jlegewie/zotfile#179]
When organizing item-files into subfolders using the `%c` wildcard in the 'subfolder' field, the resulting folder-structure changes depending on which operating system is being used.

On a Mac, an item in the collection `projects/papers` will get moved to a subfolder `projects/papers/`. I suppose this is the intended behavior.
On a Windows machine, however, the item-file instead ends up in `projectspapers/`. The names of all sub-collections within the collection-path simply get appended to one long folder name.
It looks to me like the code responsible for building the folder tree doesn't handle the Windows backslash `\` properly. This is only a guess, though, I didn't examine the code itself.

Since this makes it really hard to work on the same library across devices/OS and pretty much breaks the otherwise very useful `%c` wildcard, a quick fix would great.

**Comment by AndrewSmith2015** [comment]
I met the problem also. If my collection is "col->subcol"    ,  use   "%c"  will get a subfolder "colsubcol"  ,while what i meant is "col\subcol"!  I'm using win10 ,zotero 4.0.28 ,zotfile  4.1.6 .    
Another bug is: I drag a item from CollectionA to CollectionB , the pdf filepath will not change automatically (I have chosen "Always rename"), while what i want is to make the file in "CollectionB\"

But while use the same  setting ,another pc get a right subfolder , quite weird.

**Comment by mhl66** [comment]
Yeah, it works: changing the following line
     return getCollectionPath(collection.parent) + "/" + collection.name;
to
     return getCollectionPath(collection.parent) + "\\" + collection.name;
works as expected, for windows only, of course. The platform-independent coding should be:
     return getCollectionPath(collection.parent) + this.folderSep + collection.name;
but this **does not work**... therefore, the issue remains open, but this workaround above works, creating a windows-specific xpi file for the zotfile plugin.

**Comment by jlegewie** [comment]
Just came across this and was bored so I tried to fix it. Can someone try the current version on github on a windows pc and tell me whether it works? I don't have access to one. Mac as well, if possible.

**Comment by MikeBadescu** [comment]
Windows 7, latest Zotero standalone: worked perfectly. I selected the files, use the add-on to rename them and the files were moved to the right folders. Thank you!

**Comment by kemiisto** [comment]
I can also confirm that it works fine now both on Windows 10 and on OS X 10.11.
