### ISSUE TITLE
Renaming different files with the same filename

### ISSUE THREAD

**Issue by chasset** [jlegewie/zotfile#181]
ZotFile seems to add an index in such case. But the maximal index seems to be 99. Afterwards, all attachments with the same name are erased.

**Comment by jlegewie** [comment]
The solution is not really optimal and yes, it only iterates until 99. I didn't think anyone would use more and thought this prevents infinite loops if something goes wrong. But I can use three digits up 999. Don't se an reason to go higher though.






On Tue, Apr 21, 2015 at 2:12 PM -0700, "Pierre-Olivier Chasset" <notifications@github.com> wrote:












ZotFile seems to add an index in such case. But the maximal index seems to be 99. Afterwards, all attachments with the same name are erased.

**Comment by chasset** [comment]
I
