### ISSUE TITLE
Sync between Mac and PC

### ISSUE THREAD

**Issue by chasset** [jlegewie/zotfile#182]
ZotFile has no renamed and moved all my PDF files in a sync folder on my PC. This sync folder exists on my Mac too, but I can't access the files : the path is not "c:\users\..." but "/Users/...". Any idea to make it better?

**Comment by jlegewie** [comment]
Not sure what you mean by "sync folder"? If you are using linked attachments, there is a zotero option under "Advanced->Files and Folders->Linked attachment base directory" but that is unrelated to zotfile. If you are talking about the "send to tablet" stuff, it a different issue.
