### ISSUE TITLE
Pdf extraction: customization of the author-date parentheses

### ISSUE THREAD

**Issue by gracile-fr** [jlegewie/zotfile#186]
https://forums.zotero.org/discussion/27674/how-to-edit-xpi-files/#Comment_224188
I don't think it is (still?) possible at the moment.
Would be a hidden option (like formatNoteTitle, formatAnnotationNote, formatAnnotationHighlight, formatAnnotationUnderline)

**Comment by jlegewie** [comment]
Yes, that is currently hard coded on line https://github.com/jlegewie/zotfile/blob/master/chrome/content/zotfile/zotfile.js#L3743
`zz.replaceWildcard(item, "%a %y:").replace(/_(?!.*_)/," and ").replace(/_/g,", ")` is the relevant part. It first uses the `replaceWildcard` function and then formats the author string with `and` and `,`.

An hidden option would be good for that and I am happy to merge pull requests. Personally, I won't get to it anytime soon.

**Comment by jlegewie** [comment]
I am closing this one because it duplicates #175
