### ISSUE TITLE
Attach most recently added (rather than modified) file

### ISSUE THREAD

**Issue by julou** [jlegewie/zotfile#187]
Hello,

Thanks for this tool greatly enhancing zotero!
As stated in the feature list, "ZotFile can rename and add the most recently modified file from (…) a user specified folder as a new attachment to the currently selected Zotero item". In my experience, it would be much more convenient that the most recently added file is attached (in particular, it appends to me that files are downloaded with a modify date older than files living in my Downloads folder).

Would it be conceivable to change this and/or to define the preferred behaviour for this in the preference pane?

Best,
Thomas

**Comment by jlegewie** [comment]
On my mac, the files I just downloaded are always the most recently modified files. Not sure why that is different on your computer. Do you have a concrete link?

**Comment by julou** [comment]
on my mac, this happens when I use the download icon when hovering a pdf shown in safari and/or when I download a link to a pdf using alt-click.

does this help?

**Comment by jlegewie** [comment]
Not the case for me. You should check your Safari settings.

**Comment by julou** [comment]
So I checked again… my description was partly incorrect: the problem does not occur with the download icon shown when hovering a pdf in safari, but it does occur when using the 'download linked file' contextual menu (or its alt-click shortcut).

E.g., 1. make sure that there is a file with a recent modification date in your download folder,
2. go to http://www.pnas.org/content/107/1/127.abstract and alt-click the red pdf link in the tab bar
On my setup, the downloaded file is first when sorted by added date, but its modification date is 11/4/2010. What about you?

**Comment by jlegewie** [comment]
Yes, I can reproduce that. Here is a discussion about it:
http://superuser.com/questions/77940/can-i-get-safari-on-mac-os-x-to-set-downloaded-files-modification-time-to-curre

A couple of problems though:
1) The nice thing about modification date is that you can easily make a file the most recently modified file by re-saving it.
2) The creation date is also old so you really need the date added. I am not sure how to get that. It's not even listed in the file information on Mac OS and I can't find a variable for it in mozilla's API.

**Comment by julou** [comment]
Thanks for your answer. I set up a folder action. 

For the record the only step of this folder action is:
Run shell script (input as arguments): `touch $1`

**Comment by jlegewie** [comment]
Thanks, I did the same...  :)
