### ISSUE TITLE
Poppler Download not working

### ISSUE THREAD

**Issue by stonerl** [jlegewie/zotfile#189]
I have installed v.4.1.5.1 and use zotero v.4.0.27.
After I click on "Download & Install Poppler Tool" the button becomes inactive and says "Downloading Poppler Tools" but nothing happens

**Comment by jlegewie** [comment]
Yes, I can confirm this. I just tried to fix it. Can you retry with the version on github and report back?

**Comment by stonerl** [comment]
It is fixed. Thank you for the fast response.
