### ISSUE TITLE
Compatibility with Juris-M, please?

### ISSUE THREAD

**Issue by KarlHegbloom** [jlegewie/zotfile#191]
I am using Juris-M (https://github.com/Juris-M) rather than stock Zotero. Zotfile used to work fine with MLZ, but now not with Juris-M. Can you please fix it? I don't know how or I'd do it and send you a patch.

**Comment by jlegewie** [comment]
No idea what's going on and I wont have the time to research this anytime soon. Try an earlier zotfile version from [here](https://addons.mozilla.org/en-US/firefox/addon/zotfile/versions/) and let me know whether that works.

**Comment by adam3smith** [comment]
@fbennett -- you can probably shed some light on this? I assume this would be an easy fix.

**Comment by KarlHegbloom** [comment]
After updating everything to the latest versions it's working fine. Thank
you.
