### ISSUE TITLE
Can't download extension via Chrome

### ISSUE THREAD

**Issue by rmzelle** [jlegewie/zotfile#192]
I'm trying to download the extension from https://addons.mozilla.org/en-US/firefox/addon/zotfile/ using Chrome, but I am getting stuck behind https://addons.mozilla.org/en-US/firefox/addon/zotfile/contribute/roadblock/?src=dp-btn-primary&version=4.1.6, which only offers a download of Firefox. I can't find any link to the xpi. (I was able to download the xpi by using Firefox, but users of Zotero Standalone may not want to install it)

Some other minor nitpicks:

* https://addons.mozilla.org/en-US/firefox/addon/zotfile/ has a link ("Please consider a DONATION") to http://www.jlegewie.com/zotfile.html, which gives a 404.
* https://github.com/jlegewie/zotfile/blob/master/readme.md says "The currently released version (3.x)" which is outdated.

**Comment by rensa** [comment]
I'm having the same problem on Chrome. I'd prefer not to download Firefox if I want the xpi for Zotero Standalone, though.

**Comment by jlegewie** [comment]
Can you try again from www.zotfile.com. The download bottom should now work (not redirect to the mozilla webpage).

**Comment by rmzelle** [comment]
Great, works great. (This was of course more of an upstream problem, but ZotFile is one of the few extensions that are used outside of Firefox.)

**Comment by jlegewie** [comment]
Perfect. Linking to Mozilla was never very convenient but I tried to have a single download count.

**Comment by rensa** [comment]
All good. Thanks!
