### ISSUE TITLE
.openingQuotationMarks .closingQuotationMarks missing in Standalone?

### ISSUE THREAD

**Issue by minahilamin** [jlegewie/zotfile#198]
I have the most recent versions of Zotero Standalone and Zotfile, and I can't find the hidden option to remove/add quotation marks to my extractions in the about:config directory. I know this option was added in the 2.3 update so it might have been removed since then, but is there anyway to accomplish the same task?

**Comment by jlegewie** [comment]
I think they were replaced by the four options below, which are much more flexible.

formatNoteTitle
formatAnnotationNote
formatAnnotationHighlight
formatAnnotationUnderline
