### ISSUE TITLE
Source folder with non-ascii-name gives: "Source folder not valid"

### ISSUE THREAD

**Issue by andersjohansson** [jlegewie/zotfile#199]
I'm given this message (and the red "not valid" icon) when trying to use "/home/aj/Hämtningar/" as my source folder. This is Firefox's default download folder on my localized (sv-SE) system. I get the message when folder is set manually. When it is set to FF download folder it seems to work (it didn't before but just now when I changed the setting it did).

I started looking into the code but haven't tried to debug thoroughly. Doesn't `Zotfile.FileExist` accept non-ascii directory names? I couldn't find any good reason for that by just looking at the code.

**Comment by jlegewie** [comment]
There were always some problems with spacial characters but I never got around fixing them. I also wont be able to take a look anytime soon. If you plan to pursue this (which would be great), I recommend using the FF scratchpad. Set the environment to "Browser" and then play this the functions. For example, you can directly execute zotfile functions like this `Zotero.ZotFile.fileExists("~/Downloads/message-german.txt")`. A pull request fixing this problem would be very welcome!

**Comment by jlegewie** [comment]
Just fixed this in the version on github with https://github.com/jlegewie/zotfile/commit/cf2dede4e50dae7494db3d7cd00b93d880cddc37. Hope to update the official version soon.
