### ISSUE TITLE
Folder duplication in the renaming path

### ISSUE THREAD

**Issue by arbox** [jlegewie/zotfile#200]
Great plugin! Thank you for all the efforts!

Unfortunately I get a bit confused by the fact that I get a duplicated entry in the renaming path.

Setting the cusom location to `/home/user/Documents/Library` and using the subfolder option defined by `/%c` I can move/rename my attachments. The cue is that the attachments land under `/home/user/Documents/Library/Library/category`. I also set the hidden option `disable_renaming` to `true` since I cannot impose any patterns during bulk renamings.

Actually this behaviour started after one of the last updates but I cannot remember when exactly.
 
Is it some hidden feature of `%c`?

**Comment by jlegewie** [comment]
No, I guess it's a bug. Never used this option myself. Unfortunately, I won't have the time to fix this anytime soon so that help is welcome.

**Comment by arbox** [comment]
Ok, thank you. I'll look at it.

**Comment by arbox** [comment]
I found the real reason for this duplication, which was my fault. Consider this issue for solved.

**Comment by hyliang96** [comment]
I encountered the same problem as you. Could you share the reason you found for this duplication and how you solved it? Thank you very much!

**Comment by arbox** [comment]
@hyliang96 ,
sorry, but I cannot remember... That was something related to storing relative or absolute paths in the Zotero DB, since it's possible to switch these two options.
