### ISSUE TITLE
Download link not working

### ISSUE THREAD

**Issue by deannadel** [jlegewie/zotfile#203]
I'm trying to download ZotFile, but the download link doesn't appear to be working - is anyone else having the same problem, or have a solution? 

(When I click on "download" from zotfile.com, I get an error message saying "This webpage is not available.")

Any suggestions would be much appreciated, thanks!

**Comment by jlegewie** [comment]
Which link are you talking about? The one on zotfile.com, right?
https://addons.mozilla.org/firefox/downloads/file/325964/zotfile-4.1.6-fx.xpi?src=dp-btn-primary? 
It's working for me...

**Comment by deannadel** [comment]
Yes, it wasn't working for me yesterday, but just tried again today and it
works. Thanks!
