### ISSUE TITLE
Don't copy file pdf (but link) during bibtex import 

### ISSUE THREAD

**Issue by reyman** [jlegewie/zotfile#206]
Hi,

Actually, i have already a collection of pdf file specified for each item in my bibtex.

```
@book{Fogel2006b,
author = {Fogel, David B.},
editor = {Fogel, David B.},
file = {Attachment:/home/reyman/Bureau/tempzotero/Fogel_2006_Evolutionary Computation.pdf:application/pdf},
isbn = {978-0-471-66951-7},
pages = {296},
publisher = {Wiley},
title = {{Evolutionary Computation: Toward a New Philosophy of Machine Intelligence, 3rd Edition}},
year = {2006}
}
```

I don't want Zotero import all my pdf file in a new cryptic folder of zotero storage when i import my `.bib` file, so i try to use zotfile capacity to link pdf. 

![selection_010](https://cloud.githubusercontent.com/assets/466329/12595087/b107d20e-c479-11e5-9dac-dba435b67afa.png)

As you can see Zotero copy option is not checked in Zotfile settings. But, it seems it's not possible with Zotfile 0.4.6 version, and Zotero continue to recopy pdf when i import my bibtex.  

Is it a bug or this feature is not implemented at this time and/or work only for new item added in zotero?

**Comment by jlegewie** [comment]
Importing of bib files is unrelated to zotfile.
