### ISSUE TITLE
Rename attachment fails with invalid "lastAuthor" field

### ISSUE THREAD

**Issue by Unode** [jlegewie/zotfile#208]
The exception seems to get lost in the post processing and the pop-up only returns `{}`.
However debugging the code renders:

    exception:
        columnNumber: 1
        filename:     chrome://zotero/content/xpcom/data/itemFields.js
        lineNumber:   242
        message:      Invalid field 'lastAuthor" for base field in ItemFields.getFieldIDFromTypeAndBase()
        stack:        "getFieldIDFromTypeAndBase@chrome://zotero/content/xpcom/data/itemFields.js:242:1
                       Zotero.Item.prototype.getField@chrome://zotero/content/xpcom/data/item.js:226:17
                       Zotero.ZotFile.wildcardTable@chrome://zotfile/content/zotfile.js:1588:73
                       Zotero.ZotFile.replaceWildcard@chrome://zotfile/content/zotfile.js:1721:51
                       Zotero.ZotFile.getFilename@chrome://zotfile/content/zotfile.js:1798:22
                       Zotero.ZotFile.renameAttachment@chrome://zotfile/content/zotfile.js:3092:33
                       Zotero.ZotFile.renameSelectedAttachments@chrome://zotfile/content/zotfile.js:3219:33
                       oncommand@chrome://browser/content/browser.xul:1:1"

This didn't happen on release v4.1.7.

**Comment by jlegewie** [comment]
Just patched this. Can you confirm?

**Comment by Unode** [comment]
Confirmed as fixed.
