### ISSUE TITLE
Delete attachment in file system when item is deleted in zotero

### ISSUE THREAD

**Issue by gagarine** [jlegewie/zotfile#214]
When a item is deleted his attachment should be deleted (linked or not). Otherwise you can end up with a lot of pdf you don't want anymore. This is  a problem if you use other program to access your attachment folder.

Attachment should also be deleted if the attachment (without deleting the parent item).

Related to the #96 But I don't think we need an option to "cleanup" the folder.

**Comment by jlegewie** [comment]
This is zotero related, not zotfile. You should bring that up with them.

**Comment by zlf0625** [comment]
> This is zotero related, not zotfile. You should bring that up with them.

However, Zotero said it is not related to Zotero, since the attachments are managed by Zotfile.

See: https://forums.zotero.org/discussion/41179/zotfile-does-not-delete-pdf-files-when-a-database-entry-is-deleted
