### ISSUE TITLE
Error when renaming (this.normalize_path is not a function)

### ISSUE THREAD

**Issue by MarioJose** [jlegewie/zotfile#216]
Hi,

This error occur when renaming file:

TypeError: this.normalize_path is not a function 
(chrome://zotfile/content/zotfile.js, 1562)

I change the line 1560:

if (collection.parent == null)  return collection.name

to 

if (collection.parent == null)  return collection.name;

and it works.

Mario

**Comment by jlegewie** [comment]
Already fixed in v4.2.4. Currently under review and on github. Can you try and confirm? (but unrelated to `collection.parent`...)

**Comment by MarioJose** [comment]
Confirmed! It is working now. Excuse me, I did not see the last release (4.2.4).
