### ISSUE TITLE
Zotero+Zotfile leave orphan PDF files

### ISSUE THREAD

**Issue by Gabriel-p** [jlegewie/zotfile#228]
I have Zotero set to use a base directory, so I can sync with my laptop via Dropbox.

I have Zotfile set so that after adding an article, it will rename it following certain rules, and store it in a sub-folder (within the base folder) named after the year of publication.

After adding an article, it will be properly renamed and stored by Zotfile. If I then remove this article from my library, moving it into the recycling bin first and then *removing it from here too*, the entry in Zotero is gone as it should, but **the PDF file will remain orphaned in the sub-folder**.

This means every time I remove an entry with a PDF attachment from Zotero, I'm leaving an orphan PDF file behind.

Is there any way around this?

**Comment by jlegewie** [comment]
Hey,
1) This had nothing to do with zotfile. Zotero deletes attachments not zotfile. 
2) I believe that the behavior you describe is intentional for linked attachments. As the name suggests, these are "links". Deleting links should never delete the original file. 

Sorry that I can't help with this.

**Comment by Gabriel-p** [comment]
Too bad, I reported this at the Zotero forum and was told basically "this will behavior not be changed". The difference is that if I delete an entry *not linked* via Zotfile, the PDF file actually gets erased. If I use Zotfile to rename+move files, every time I delete an entry, an orphan PDF is left behind.

Thanks anyway.

**Comment by jlegewie** [comment]
Still has nothing to do with zotfile. Zotfile just creates a "Linked Attachment". You can create them from Zotero too. It just depends on the type of attachment you use ("Linked" or "imported"). Both are zotero attachments. Zotfile just allows you to decide, which type of Zotero attachment you want to create.

**Comment by Gabriel-p** [comment]
Yes, I understand. I'm not saying it is an issue with Zotfile, just that it'd be an nice option to have. I just requested it over at the Zotero forum.
