### ISSUE TITLE
Renaming non-pdf attachments error on non-default user profiles

### ISSUE THREAD

**Issue by quctex** [jlegewie/zotfile#235]
Steps to reproduce:
1. Create new user profile by run "zotero.exe -p" and load this profile;
2. Set "Base directory" in Zotero preferences. Install ZotFile and set same directory  as "Custom Location" in ZotFile General Settings; (also set any other custom directory in "Source Folder for Attaching new files" section);
3. Attach a link to pdf file into existing item "First steps...";
4. Try to rename this pdf attachment. Renaming completes correctly.
5. Attach a link to djvu file into existing item "First steps...";
6. Try to rename this djvu attachment. Renaming stops with error

> Attachments skipped because they are top-level items, snap-shots, or the file does not exists

In the default user profile any attachments renames correctly. 
Zotero Standalone 4.0.29.10;
ZotFile 4.2.6;
Windows 7 x64.

**Comment by jlegewie** [comment]
This is probably related to your settings in the new profile. Check Zotfile Preferences -> Advanced settings -> "Only work with the following filetypes". You can add djvu to that list or disable the preference entirely. Does that solve the problem?

ps: The files also have a .djvu extension and are kind of an alternative pdf format, right?

**Comment by quctex** [comment]
Oh, thanks! This is solve problem!
