### ISSUE TITLE
Problem seeing new file in the source folder

### ISSUE THREAD

**Issue by Jmuccigr** [jlegewie/zotfile#237]
Occasionally Zotfile won't recognize that a new file has been added to the source folder which I've got set to my Downloads folder. Instead it sees the previously added file. If I "touch" the file, then Zotfile will see it. Not sure it isn't just my sometimes slow spinning hard drive, but don't know how to check that either.

Zotero standalone 4.0.29.5, Zotfile 4.2.6, OS X 10.9.5

**Comment by jlegewie** [comment]
Are you talking about the "watch folder" functionality with the popup "Click here to add file"?

**Comment by Jmuccigr** [comment]
Yes.

Under Zotfile's "General Settings" pref pane, "Watch for new files in source folder" checked, "custom:" set to ~/Downloads. Location of files is set to "attach stored copy of file(s)."

**Comment by jlegewie** [comment]
Unfortunately, I will most likely remove that feature in 5.0. 5.0 doesn't really include anything new, just a rewrite of most code to be compatible with Zotero 5.0. "Watch folder" was always kind of a hack, which made it resource inefficient (in some cases) and resulted in a number of problems like the one you describe.

**Comment by Jmuccigr** [comment]
Too bad. It's a handy feature when it's working well.

**Comment by gracile-fr** [comment]
@jlegewie : is there anything specific to Zotero 5.0 which makes impossible/difficult to port the Watch Folder function? Or are you bored to troubleshoot and debug it (which I would understand)?

**Comment by jlegewie** [comment]
No, still possible but there are two reasons why I didn't include it in zotfile 5: a) the implementation always wasn't optimal and potential resource hungry and b) removing that functionality reduced the substantial amount of work required for porting zotfile to Zotero 5.

**Comment by janbaykara** [comment]
@jlegewie could you port this function to a separate plugin? Or at least highlight the commits that removed the functionality, for others (me, perhaps) to create a separate plugin later?

**Comment by 3180100753** [comment]
@jlegewie i agree with janbaykara .Could you port this function to a separate plugin?
