### ISSUE TITLE
Error in zotfile.js when trying to automatically move and rename attachments

### ISSUE THREAD

**Issue by joelostblom** [jlegewie/zotfile#238]
I keep getting this error `TypeError: win.ZoteroPane.itemsView.saveSelection is not a function(chrome://zotfile/content/zotfile.js, 3248)` when I have Zotfile set to automatically rename and move attachments. The selected article is added to Zotero, but the attachments are not moved and renamed.

This never happens when I right click and item and manually click rename attachments, and typically only happens to the first paper I try to add to Zotero in a new Firefox session. Can I do anything to fix this so that attachments are always automatically moved and renamed?

**Comment by joelostblom** [comment]
Forgot to mention: I am on Firefox 47.0, Zotfile 4.2.6 and Antergos Linux (arch derivative) kernel 4.6.1-2.

**Comment by jlegewie** [comment]
Can you give some details about Zotero setup etc? Are you using Zotero Standalone? What exactly are the steps that reproduce this from starting zotero to the error?

**Comment by joelostblom** [comment]
I am using the Zotero addon for Firefox, not the standalone version. I have Zotfile setup to move all new attachments to a folder in my SpiderOak from the default Zotero location. The steps to reproduce are launching Firefox, navigating to a journal article with a pdf that I would like to save, and press the 'Save to Zotero'-icon in the browser toolbar.

I tried it more extensively now and notice that the error persists for all articles I download, until I open the Zotero pane and right click >> Manage Attachments >> Rename Attachments. This works without error messages and, curiously, makes Zotfile work automatically with all subsequently downloaded articles. So after I have done the manual renaming once, I can use the Zotero toolbar button to download article pdfs and Zotfile will automatically rename them.

I do use NoScript and some other addons, not sure if that would interfere somehow.

**Comment by jlegewie** [comment]
Mmh, I can't reproduce this. I suggest that you wait for 5.0 and see post again if the problem persists. 5.0 is mainly for compatibility with Zotero 5, which necessitates changes to many parts of the code. Might still be a couple of weeks though...

**Comment by joelostblom** [comment]
Hi @jlegewie,
I am in a period where I use Zotero (4.2.8) quite frequently, and I keep encountering the issue I originally reported above quite often.

I am thinking of pulling the 5.0 branch from GitHub, and running it while waiting for the official release. Are there any major caveats with 5.0 that would make you recommend against using it for everyday use?

**Comment by bwiernik** [comment]
4.2.8 is really old and out of date. The current version is 4.0.29.15. You could try to update to the current version of 4.0.x first. If the problem persists, the Zotero 5.0 beta and Zotfile 5.0 beta are both really stable at this point, and you probably won't encounter any problems using them. But do make a backup of your Zotero database first before upgrading just in case.

**Comment by joelostblom** [comment]
Great, I will try out 5.0 beta later today!

I didn't know 4.2.8 was old. I got it from the Mozilla Addons download page and it says it was updated on February 4th 2017. Should I always download Zotfile from Github then instead of the Mozilla Addons page, even after the 5.0 release?

**Comment by bwiernik** [comment]
You said Zotero 4.2.8, not Zotfile. Zotfile 4.2.8 is the current version.

**Comment by joelostblom** [comment]
Sorry, my mistake. I am running Zotfile 5.0.0b2 on the Zotero 5.0 Beta now. No issues after the first day, will reopen if anything comes up.
