### ISSUE TITLE
PDF annotation extraction fails for files with uppercase extension (*.PDF)

### ISSUE THREAD

**Issue by minj** [jlegewie/zotfile#241]
Problem lies on [this line](../blob/3175c740be874cad50887ff87504d7582472fbf4/chrome/content/zotfile/zotfile.js#L3671)

`Zotero.ZotFile.getFiletype` should perhaps always return lowercase extensions but that needs to be first checked against usage to prevent bugs on case-sensitive file systems.

Should be a quick fix really but if necessary I will make a PR when I have time..

**Comment by jlegewie** [comment]
I think that is already fixed in the 5.0 branch. 5.0 is purely for compatibility with Zotero 5.0, which requires a lot of code changes. It's still going to take a little though. Zotero 5.0 is planed for the beginning of October and I hope zotfile 5.0 is ready by then as well...
