### ISSUE TITLE
Play nice with zotero-better-bibtex

### ISSUE THREAD

**Issue by dgerber** [jlegewie/zotfile#246]
See https://github.com/retorquere/zotero-better-bibtex/issues/552 . [This branch](/dgerber/zotfile/tree/compat-bbt-2) makes minimal changes to zotfile so that it can share its renaming patterns with BBT:
- [x]  Evaluate wildcards lazily to avoid both libs calling each other recursively.
- [x] Expose BBT's citation key to zotfile patterns as `%b`.
- [ ] Commit to an API to get an item's filename from outside (BBT). It seems to be `ZotFile.getFilename(zitem)`.

**Comment by jlegewie** [comment]
Thanks. I would appreciate a pull request for this (5.0 branch)...

**Comment by dgerber** [comment]
So, it's implemented but not tested at all!

**Comment by jlegewie** [comment]
Are there any remaining problems here or can I close this issue? The zotfile API is `Zotero.ZotFile.getFilename(item, name)` where item is a top-level Zotero.Item (not the attachment) and name is the current filename as fallback and for file extension.

**Comment by dgerber** [comment]
It was implemented in [PR246](https://github.com/jlegewie/zotfile/pull/249). It won't work if not merged into master...

**Comment by jlegewie** [comment]
Ups, I somehow missed that. Can send a pull request for master and remove all the unnecessary spacing changes? Happy to take separate pull request for formatting but it pollutes this one.

**Comment by jlegewie** [comment]
Sorry, I am not really up to date. What is the status of this?

**Comment by dgerber** [comment]
Hi, you were just waiting for a separate pull request for whitespace cleanups, but I don't depend on this anymore and have no plan to do this extra work for now, sorry.
