### ISSUE TITLE
zotfile 5 beta doesn't work with Zotero 5 beta standalone

### ISSUE THREAD

**Issue by mpenguin** [jlegewie/zotfile#250]
I was following the directions to create the XPI file, but Zotero standalone would not install, saying it was not compatible with Zotero 5.0.

I opened the install.rdf file and noticed this:

```
<em:targetApplication>
	<Description>
		<em:id>zotero@chnm.gmu.edu</em:id>
		<em:minVersion>3.0b1</em:minVersion>
		<em:maxVersion>4.*</em:maxVersion>
	</Description>
</em:targetApplication>
```
I updated the maxVersion to "5.*", saved it, and then made the .xpi - worked like a charm. Zotfile is now running; I'll report any futher bugs I encounter.

**Comment by jlegewie** [comment]
Thanks. Just fixed that and also set minVersion to "5.*".

And please do report any bugs. Systematic testing of the different features would also be great.
