### ISSUE TITLE
ZotFiIe Error: better info 

### ISSUE THREAD

**Issue by Gettyk** [jlegewie/zotfile#254]
Thanks a lot for Zotfile, it's really a great plugin for zotero! 
I have just a suggestion. When renaming (and changing the folder of my whole library) I got two errors. I could related the first error to the fact that my pdf didn't have any metadata except a title.  But I am clueless about the second one. In brief, it would be great to have better info about why a renaming is failling instead of these popups:

Error when moving the file 'filename.pdf' (Exception... "Component returned failure code: ox80520012 InslFiIe.moveTol" nsresult: "Ox80520012 location: "JSframe :: chrome://zotfile/content /zotfile.js :: Zotero.ZotFiIe.moveFiIe :: In 2025" data: no)). 

Error when moving the file 'Chat orange.pdf' (Exception... "Component returned failure code: Ox80520012 InslFiIe.moveTol" nsresult: "Ox80520012 location: "JSframe :: chrome://zotfile/content /zotfile.js :: Zotero.ZotFiIe.moveFiIe :: In 2033" data: no)).

**Comment by jlegewie** [comment]
Do you have a reproducible example for this? What do you mean with metadata for the pdf? Do you mean the zotero item has no metadata? Or the actual pdf file?

Thanks!

**Comment by Gettyk** [comment]
Just create a .pdf from a MS word (save as .pdf) and then add that pdf to zotero. Because the pdf doesn't have any metadata, zotfile is not able create a parent item. So I have to do it "manually" by right clicking and selecting "Create a parent item". The zotero metadata is empty except the title which is the filename. Then if I right click and select management attachement/rename, I get the error. For that example I got the error line 2033. I am not sure what the difference is between the error line 2033 and 2025, as they both seems to be triggered by missing metadata. 

So in brief, both metadata are missing : the .pdf metadata but also the zotero metadata (except the title, item type, date added and date modified).

**Comment by jlegewie** [comment]
Actually, I can't reproduce this. Which Zotfile version are you using? What is your renaming rule?

**Comment by Gettyk** [comment]
Sorry I didn't see you reply. In zotfile for zotero5 I don't have the bug anymore!
