### ISSUE TITLE
ZotFile 5 not working with Zotero 5

### ISSUE THREAD

**Issue by jamespl87** [jlegewie/zotfile#255]
Hi,

I have installed Zotero 5.0-beta.r91+99cd11e. I have also uninstalled & installed Zotfile 5.0.0b2 a couple of times. I'm using Zotero Standalo.

The Zotfile plugin is installed correctly, and supposedly loaded up. However, it is completely unresponsive / not working.

I cannot access the 'Preferences' button from the Add-Ons manager: it just does not open a dialogue box. And there is no contextual menu on the right click to perform any functions. No functions are automatically triggered either.

Assistance would be much appreciated.

Thanks, James

**Comment by jlegewie** [comment]
I can't confirm. Everything is working for me in Zotero Standalone 5.0-beta.r91. I won't be able to provide further support without more details.

**Comment by jamespl87** [comment]
Is there a log file or debug mode I can run to help?
Most definitely not working.

**Comment by jlegewie** [comment]
Here are some guidelines: http://zotfile.com/#reporting-a-bug
Maybe you should also post on the Zotero forum to see whether others have the same problem.

**Comment by GCamp6** [comment]
I installed Zotero-5.0-beta.134+0570c2e. In the Add-ons manager ZotFile 4.2.8 is declared uncompatible

**Comment by GCamp6** [comment]
Installed Zotero-5.0-beta.134+0570c2e and ZotFile5 as described in https://github.com/jlegewie/zotfile/tree/5.0 . Everything seems to be smooth for the moment
