### ISSUE TITLE
[troubleshooting] renaming rules not updating

### ISSUE THREAD

**Issue by hmarten** [jlegewie/zotfile#256]
thanks for this great plugin --
not sure if this is the right place to post. I've successfully downloaded and installed zotfile and having been playing with the renaming rules to suit my preferences, but they seem to have become stuck.  In the plugin preferences, I have for "Format all types except patents":

{%a } - {%t} ({%y})

with "Change to lower case" checked, and the "Use Zotero to rename" box unchecked (checking it doesn't seem to make a difference). When i use the "Update" button in preferences (for a preview of the renaming rules) it works correctly, e.g. it will show:

walton - ramus and bacon on method (1971)

But if I actually run "Rename File from Parent Metadata" in Zotero, the file will be renamed in this format (for comparison):

Walton - 1971 - Ramus and Bacon on method.pdf

These settings correspond to a previous set of renaming rules (i've been trying different rules); it worked correctly at first but, like i said, it seems to be stuck with an older set of renaming rules that won't update. I have tried removing and reinstalling the plugin after re-downloading, restarting Zotero, restarting my computer, etc., and nothing seems to work. Any help would be much appreciated, and my apologies if this is the wrong place to pose troubleshooting questions like this. thanks -

**Comment by jlegewie** [comment]
Glad that you like the plugin. Can you please use the Zotero forum for support questions. Github is for bug reports and features requests.
