### ISSUE TITLE
items not removed from tablet saved searches

### ISSUE THREAD

**Issue by ookimi** [jlegewie/zotfile#257]
So yes - tablet items are not removed from tablet saved searches even when I try to get things from tablet.
I'm using zotero 4.0.29.16 on Ubuntu 16.04 64 bit, zotfile 4.2.6
The files themselves are moved back and forth between the table folder and main zotfile folder. But the items in the saved search are not removed. Not all of them even have those _tablet tags for some reason - but they won't be removed from the search irrespective of that.
I tried to remove the search by deleting it and reinstalling zotfile - but the same items are still listed under tablet files and won't be removed, even if I get the attachments back.

**Comment by jlegewie** [comment]
Can't reproduce. Please provide step by step instructions to reproduce in Zotero 5 and ZotFile 5
