### ISSUE TITLE
Error: TypeError: f.exists is not a function when sending files to tablet

### ISSUE THREAD

**Issue by PaBLoX-CL** [jlegewie/zotfile#258]
I removed the files by hand from the folder, and now I'm getting this error when trying to send/get the files from the tablet:

    Error: TypeError: f.exists is not a function

It also says that the files doesn't exist, and I can't try to replace them either. I tried removing the tag (since it appears on the saved search), but the issue persists and keeps appearing in the search. So it looks like there's a problem with some kind of zotero or zotfile database, that still thinks the files are "there".

I've tried to search through the issues here and in google, but I can't find any leads.

------------

Sometimes, I also get this error: 

    TypeError: tablet_file.exists is not a function (chrome://zotfile/content/zotfile.js, 2790)

**Comment by jlegewie** [comment]
Please use zottige 5.0 beta (available from [here](https://github.com/jlegewie/zotfile/tree/5.0)) and post the exact steps to reproduce the error here. Otherwise, you can use the Zotero forum for support requests. In general, you should not manually move are delete files that are managed by zotero.

**Comment by PaBLoX-CL** [comment]
Maybe it wasn't clear, but I removed the file from the folder that I use it to move files between zotfile and my tablet (the one is set from the zotfile preferences). So there aren't managed by zotero. That's why I believe this is a zotfile issue, not zotero.

I'll try zotfile 5.0 anyway.

**Comment by jlegewie** [comment]
And the exact steps, please. Like 1) ..., 2) ... so that it's easy to reproduce.  Thanks.

**Comment by PaBLoX-CL** [comment]
I was using latest stable zotero, but it says is not compatible with that version. I'm supposed to try using zotero 5.0 too?

**Comment by jlegewie** [comment]
Yes, Zotero 5 beta. You can also wait until that comes out officially.

**Comment by PaBLoX-CL** [comment]
Ok, now I can re-send the files again to the tablet and they are getting moved there. Thanks! The send to subfolders stopped working though. Is this a known issue or should I create a new issue?

**Comment by jlegewie** [comment]
Not a known issue
