### ISSUE TITLE
5.0: Send to Subfolder on Tablet not available in zotfile 5.0

### ISSUE THREAD

**Issue by PaBLoX-CL** [jlegewie/zotfile#259]
I'm using zotero 5.0beta and zotfile 5.0. Since the upgrade, in the contextual menu there no option to send subfolders. Even when it's configured in the zotfile preferences.

![image](https://cloud.githubusercontent.com/assets/275754/21807951/cffb67ac-d71f-11e6-9ddc-523f069f476d.png)

I don't know if those "warning" advices are normal, or expected to be there.

**Comment by jlegewie** [comment]
Actually, nothing is working for you (not just the subfolders). Can you double check the version, check error message etc?

**Comment by PaBLoX-CL** [comment]
It's correctly sending files to the tablet though. There's no error, because the option isn't available.

The versions are:

zotero: 5.0-beta.105+8c2c097
zotfile: 5.0.0b2

**Comment by PaBLoX-CL** [comment]
Is there any more information do you need? I tried this on three different systems.

**Comment by jlegewie** [comment]
Can you make sure that you have the most recent version from https://github.com/jlegewie/zotfile?
I did not update the version number with very commit...

**Comment by PaBLoX-CL** [comment]
I understand. I cloned the repo, checkout to the 5.0 tree. And ran `make` from there. I installed "from xpi file" as in the `readme.md`. The number version doesn't change of course, but I'm building it from the last commit on nov 17.

I don't mean to be obnoxious, I really like zotfile. I'll try to uninstall everything and reinstall zotero when I get home.

**Comment by pablox-cl** [comment]
I was waiting for Zotero to be officially updated. Right now I'm running Zotero 5.0.4 and Zotfile 5.0.2, and with the latest xpi built from master branch (last commit from today). I'm still seeing the same issue :/. Any idea how can I debug it?

**Comment by jlegewie** [comment]
Zotero 5, right? You should check the error console as described here: http://zotfile.com/#reporting-a-bug

**Comment by cborkenhagen** [comment]
Hi there, I'm having what looks to be the same issue. My info:

MacOS 10.12.5
Zotero 5.0.4
Zotfile 5.0.2

Error log gives the following error:
`[JavaScript Error: "collection.getParent is not a function" {file: "chrome://zotfile/content/ui.js" line: 147}]
`

Let me know if any other information would be helpful. Thanks!

**Comment by jlegewie** [comment]
What are your Zotfile settings? Do you use "Tablet Settings -> Create subfolders from zotero collections"? or "Use additional subfolders defined by"?

**Comment by cborkenhagen** [comment]
The problem arises when I select the "Create subfolders from Zotero collections" option. I just tried switching to "Use additional subfolders defined by..." and that's working just fine.

**Comment by jlegewie** [comment]
I just pushed a change to github that might fix this. Can you try?

**Comment by cborkenhagen** [comment]
Just tried it, and it works! Thanks a ton. 

I'll play around with it a little more and post problems here, but so far it works in each of the scenarios I've tried (paper in multiple collections, subcollections, etc.).

**Comment by jlegewie** [comment]
Please do let me know how it goes and note that I pushed a second change maybe 5-10 min later. Make sure that you use that version from github.

**Comment by cborkenhagen** [comment]
Got it. I'll dl again to be sure I'm on the latest version. Thanks again.
