### ISSUE TITLE
5.0: zotero options to move get/send from tablet dissapears after right clicking on a item from a group library

### ISSUE THREAD

**Issue by PaBLoX-CL** [jlegewie/zotfile#260]
I understand as of #159, it's not possible to get/send files from tablet. The issue here is that after going to the context menu of an item on a group, they disappear from every item.

Steps:
1. Create group
2. Have a pdf in the group
3. Right click on that item, and get the `Selected item is in group library`
![image](https://cloud.githubusercontent.com/assets/275754/22186218/e99a84ee-e0d0-11e6-9d3e-bbae5340134a.png)
4. Right click on any other item
5. Get the same context menu
6. Restarting zotero "fix" it

**Comment by jlegewie** [comment]
Thanks for the exact report but I can't reproduce this even when I follow the steps exactly. Any idea? Something else going on?
