### ISSUE TITLE
5.0: Links in extracted annotations stopped working

### ISSUE THREAD

**Issue by jlegewie** [jlegewie/zotfile#261]
Probably related to this: https://github.com/zotero/zotero/commit/dc04a1231cad3b8e092d963c53fc926b3fdf315d
https://github.com/zotero/zotero/commit/044ecf21577e65563e3abfd9602d20d2f462d535

> Extracting annotations works as expected with Zotfile (5.0.0b2 + Zotero 5beta119). However, whenever a link in the extracted zotero note is clicked, and the option "Open link" is chosen a) no link is opened and b) all links in the note are being removed. I.e. "Open link" behaves as I would expect from "Remove links".

Relevant plugin:
https://github.com/zotero/zotero/commit/dc04a1231cad3b8e092d963c53fc926b3fdf315d#diff-2cd101881dd34f251168e4cb1144149a

https://github.com/zotero/zotero/pull/450

Copy and paste problem:
https://github.com/zotero/zotero/pull/452

**Comment by mtd91429** [comment]
I noticed this behavior yesterday and posted to the forums
[https://forums.zotero.org/discussion/64082/5-0-beta-links-are-being-deleted-in-notes](https://forums.zotero.org/discussion/64082/5-0-beta-links-are-being-deleted-in-notes
)

I definitely could be wrong, but I think that the link removal is occurring during the sync process and is unrelated to TinyMCE. 

1. Notes that aren't altered continue to contain Zotero links generated before the 5.0 upgrade. They only disappear after a change has been made to the note (and with a delay).

1. I installed the latest build of zotero into a nightly firefox and didn't sign in. In this context, the link deletion doesn't occur. 

1. I also tested this on my own reference database using the most recent beta build (`5.0-beta.120+3415aae`). The links are deleted with a delay after inserting them into a note or after altering a note. However, they are immediately deleted if you push a manual sync. After I unlinked my account, the links don't disappear.

Finally, if you look at the debugging log I posted [here](https://gist.github.com/mtd91429/970cede8bbfdd6e639f2fec204927845#file-zotero_debug_vanishinglinks-txt-L211-L287), the href is present up until the HTTP POST is performed.

I've been looking through the syncing files https://github.com/zotero/zotero/tree/master/chrome/content/zotero/xpcom/sync in Zotero trying to determine what is the origin, but haven't any luck (the origin may be beyond my knowledgebase, or my hypothesis is incorrect).

**Comment by jlegewie** [comment]
Thanks for your comments. I opened a ticket at the zotero repro because it affects zotero links as well and has to be fixed on their side. Maybe you should report your observations there as well: https://github.com/zotero/zotero/issues/1163
