### ISSUE TITLE
Can't uncheck 'Source folder'?

### ISSUE THREAD

**Issue by Gabriel-p** [jlegewie/zotfile#263]
I just installed the latest 5.0 build from Github. This is what I see if I empty and then try to uncheck the 'Source folder':

![captura realizada el 2017-02-02 10 08 56](https://cloud.githubusercontent.com/assets/6054951/22550610/a397a3ca-e92f-11e6-98b4-93bb3962e2c2.png)

i.e.: I can't remove the check. After close/re-open the Preferences, I see:

![captura realizada el 2017-02-02 10 09 47](https://cloud.githubusercontent.com/assets/6054951/22550632/c090c4c0-e92f-11e6-996a-10255306fcf2.png)

which I assume is because I left the field empty.

I'm running Zotero 5.0-beta.128+26eebcf on elementary OS Loki 56 bit (based on Ubuntu 16.04)

**Comment by jlegewie** [comment]
What do you mean with "uncheck"? Do you mean change to "Use FF download folder"?

**Comment by Gabriel-p** [comment]
No, I mean 'select neither option'. I intended to not select any folder.

At first I mistook this for the 'monitor folder' option, now I see that it is not so it's a very minor issue really.

**Comment by jlegewie** [comment]
It's not possible to select neither option and yes, this has nothing to do with 'monitor folder'. The 'monitor folder' feature was removed in 5.0
