### ISSUE TITLE
5.0: 'New attachment' window doesn't go away

### ISSUE THREAD

**Issue by Gabriel-p** [jlegewie/zotfile#265]
After using the Zotero connector to add an item, Zotfile renames the attachment and the little bottom-right window never goes away:

![captura realizada el 2017-02-06 12 04 39](https://cloud.githubusercontent.com/assets/6054951/22652232/768fcc8a-ec64-11e6-98b4-7d5656ed6702.png)

I have to close/open Zotero to make it disappear.

**Comment by jlegewie** [comment]
I know... Here is a temporary solution until this gets fixed: Just click on it.

**Comment by Gabriel-p** [comment]
It didn't occur to me to just do that... :confused: Thanks!

**Comment by Gabriel-p** [comment]
This issue appears to have gone away with v5.0.0b2.
