### ISSUE TITLE
5.0 Manually renaming a file title does not update filename

### ISSUE THREAD

**Issue by conchra** [jlegewie/zotfile#271]
Originally thought to be a Zotero error (see https://forums.zotero.org/discussion/comment/270684) debug ID is D1855057273.

If I rename a file (e.g. pdf), by right-clicking on the name in the right-hand panel and making sure that "Rename associated file" is checked the following occurs:
1. File is renamed at the top of the right-hand column (in bold)
2. The file is renamed on the computer in "storage\[random folder]"
3. The "Filename" property in the right-hand column is NOT renamed/updated
4. When I double-click on the file in the centre pane, the error " File not found" comes up.
5. I can find the file with the new name in Windows Explorer and reattach

Using right-click "Rename File from Parent Metadata" or  Zotfile's "Manage Attachments|Rename Attachments" works fine. Disabling Zotfile prevents the problem.

Zotero Version 5.0-beta.142+bb0fa73 
Zotfile 5.0.0b2
[debug.txt](https://github.com/jlegewie/zotfile/files/795364/debug.txt)

**Comment by jlegewie** [comment]
Sorry, I can't reproduce this and don't think it's possible that zotfile is responsible. Not 100% sure though.

**Comment by conchra** [comment]
Thanks for looking into this. I was original led to believe that it was not a Zotero 5 beta problem, but then it turned out that it was.
