### ISSUE TITLE
blank window appears when Link Opens

### ISSUE THREAD

**Issue by TheKiteRunning** [jlegewie/zotfile#272]
A useless blank window appears when a link of a note or content is clicked.

The problem is shown as below.

![image](https://cloud.githubusercontent.com/assets/24802332/23241621/0cd01518-f9af-11e6-9ea1-a09f024b419a.png)

What's worse, the tools bar of the window does not show at the same time

![image](https://cloud.githubusercontent.com/assets/24802332/23241753/e3094064-f9af-11e6-9995-47c49da98afd.png)

Thanks

**Comment by jlegewie** [comment]
Thanks. That's a known issue and there is hope for 5.0 because it got fixed in Zotero but I haven't managed to apply that to zotfile.
