### ISSUE TITLE
Feature Suggestion: Store all files for webpage snapshots as one archive file (e.g. .tar)

### ISSUE THREAD

**Issue by OmidS** [jlegewie/zotfile#274]
_I was originally thinking of suggesting this as a core Zotero feature, but I think it may also make sense as a feature in Zotfile._ 

**Problem:**
Every time Zotero takes a snapshot from a webpage, hundreds of files (images, js, css, etc) are added to the Zotero data directory. This makes taking backups from the Zotero data directory, moving it around, or syncing it with cloud services like Google or Dropbox more difficult.

**Suggested Solution:** 
Add the option to store web snapshots as one archive file. When later Zotero is opening a snapshot, the archive file can be extracted in a temp directory just before opening. 

Any archiving format would work. It doesn't need to (and probably for the sake of performance shouldn't) do any compression, so tar, tar+gzip, zip, etc all should be fine. Perhaps the option with the best library support is the best option. 

**Assessment of difficulty:**
An archiving library is required so that Zotero can archive/extract the snapshot files. As long as such library is available (a quick search shows that there are some open source options such as [jszip](https://github.com/Stuk/jszip), [zip.js](https://github.com/gildas-lormeau/zip.js), [js-untar](https://github.com/InvokIT/js-untar), [tar-js](https://github.com/beatgammit/tar-js)). The rest should not be very difficult. A couple of hooks for when a new snapshot is created, or a snapshot is opened. Although I am not really familiar with Zotero or Zotfile code so I may be missing some obvious things. Please let me know if that is the case. 

I would be happy to hear any feedback or advice. Can this feature fall under the Zotfile area of work? If so, and if implementing it is not very difficult, I may even be able to contribute it myself.

**Comment by jlegewie** [comment]
Sounds like it makes sense but I won't have to time to add and maintain it in zotfile...
