### ISSUE TITLE
5.0 beta: Files not renaming, not auto-recognising on download

### ISSUE THREAD

**Issue by janbaykara** [jlegewie/zotfile#276]
In the 5.0 beta (5.0-beta.167+b732a82), Zotfile is:

- not auto-recognising files for appending, on download
- not renaming files on appending to items

**Comment by jlegewie** [comment]
First feature was removed (which has been discussed). Can't do anything about second feature without steps to reproduce.

**Comment by janbaykara** [comment]
@jlegewie On point 2, the filename remains the same instead of renaming, upon drag-dropping a PDF to the item.

**Comment by jlegewie** [comment]
I won't port myself and said multiple times why. The functionality was mainly in the `watchFolder` function [here](https://github.com/jlegewie/zotfile/blob/master/chrome/content/zotfile/zotfile.js#L194).

Automatic renaming works for me. Drag/Drop file and it gets renamed. Same for browser extension.
