### ISSUE TITLE
Zotfile is incompatible with Zotero 5.0-beta.180+de7b56b

### ISSUE THREAD

**Issue by Gabriel-p** [jlegewie/zotfile#279]
I'm running Zotfile v4.2.8. Today Zotero updated to v5.0-beta.180+de7b56b and now Zotfile is disabled saying it is not compatible with this new version.

![captura de pantalla de 2017-04-18 10-57-11](https://cloud.githubusercontent.com/assets/6054951/25134410/e076574c-2425-11e7-8a65-632c215b4437.png)

**Comment by Gabriel-p** [comment]
Also, how am I running Zotfile v4.2.8 when the latest release is v4.2.4??

https://github.com/jlegewie/zotfile/releases

**Comment by jlegewie** [comment]
Zotfile v4.2.8 is not compatible with Zotero 5.0. You have to use the the zotfile beta in the 5.0 branch on Github (https://github.com/jlegewie/zotfile/tree/5.0).

**Comment by Gabriel-p** [comment]
Well that explains it. Sorry, forgot about the 5.0 branch. Thank you!
