### ISSUE TITLE
Automatic renaming of newly added entries not working

### ISSUE THREAD

**Issue by fungs** [jlegewie/zotfile#281]
Hi,

I can't get the automatic triggering of the PDF attachment renaming to work. If I add an entry either using the site-specific Zotero import plugin in Firefox or using the PDF annotation and metadata retrieval function in Zotero, I have to manually click on the new entry and select "rename attachment". I believe that I have checked all the relevant boxes in the settings.

**Comment by jlegewie** [comment]
I can't reproduce this. If you still have the problem, provide step by step instructions using Zotero 5.x with Zotfile 5.x

**Comment by fungs** [comment]
I cannot say how and when, but automatic renaming seems to work again for me in the 5.x branch of zotero.

**Comment by tkietzma** [comment]
So you can drag and drop PDFs and they get moved automatically? Too bad it was not resolved explicitly, I was hoping for you to have the answer: https://xkcd.com/979/

Anyone else with pointers?

Thanks again!

**Comment by ammoniac1984** [comment]
Same problem here. Using Zotero 5.0.58 and Zotfile 5.0.9 on MacOs 10.12

**Comment by fungs** [comment]
For me, somewhere along the way it started working, again.

**Comment by oscarmorrison** [comment]
Hey. I am having exact same issue as described: https://github.com/jlegewie/zotfile/issues/281#issuecomment-398022470

I mainly use the safari Zotero importer. If the imported imports a .pdf I then have to right click and rename attachment to get desired result.

Is this expected behaviour, or should this be automatic?

**Comment by ryqiem** [comment]
Same problem here! Zotero 5.0.86-beta.2, would love for Zotfile to rename imports.

I drag/drop a pdf into Zotero, it creates a new entry and renames according to Zotero (not zotfile) renaming rules.

**Comment by julianirwin** [comment]
I'm having this issue on Windows 10 with Zotero 5.0.92 and Zotfile 5.0.15.

**Comment by FlorinZai** [comment]
Same for me, does not automatically rename to zotfile when linking Zotero 5.0.93 and Zotfile 5.0.15. Have to click to rename

**Comment by lonelykid** [comment]
Zotfile is trigger with the Chrome extension, but not trigger when dragging pdf into Zotero, either when you let Zotero retrieve automatically or manually click retrieve metadata.

**Comment by jonathan-sahar-tau** [comment]
same here!

**Comment by elenx3** [comment]
same goes for me. When I add an pdf I have to rename it manually in order to get the correct renaming rule and the correct linking to my expected folder.

**Comment by FlorinZai** [comment]
Same for me, automatic renaming should be fixed

**Comment by darcyalcantara** [comment]
Same here.
