### ISSUE TITLE
Not compatible with symbolic link on Mac

### ISSUE THREAD

**Issue by lifeforaiur** [jlegewie/zotfile#282]
I'm moving my Zotero attached pdfs to a new location, by using the "rename" feature. However, when selecting the "Location of Files" -> "Custom Location", it turns out Zotfile can not work well with symbolic link folders. It will tell rename not successful, not able to move the file to a new location.

Is there any way to work around this?

Thanks!

**Comment by jlegewie** [comment]
Why don't you just use the absolute path for zotfile preferences?
