### ISSUE TITLE
Extracting notes moved the highlighting

### ISSUE THREAD

**Issue by Jmuccigr** [jlegewie/zotfile#284]
I just re-imported a PDF after annotating it in Preview.app. Zotfile did the note extraction, but the highlights got moved during the process and the resultant file had them in the wrong place and also had them containing no text (when I tried to extract them with Skim).

**Comment by jlegewie** [comment]
The extraction of annotations in Zotfile does not modify pdf file so I guess something else is responsible....

**Comment by Jmuccigr** [comment]
Well, whatever it is, it just happened again on a different document. Maybe it's Preview, but it's definitely happening.
