### ISSUE TITLE
Erasing file from tablet causes all sort of errors

### ISSUE THREAD

**Issue by raffam** [jlegewie/zotfile#285]
Hi,
if you send a file to the tablet it gets copied to a folder of your choice. If you delete the file from that folder manually, ZotFile seems unable to recover from that

First, you cannot "get the file from tablet" as it fails and stay as it is. It should fail and recognize that the file was deleted, thus recovering. "recovering" means for ex. pretending the file was not sent in the first place, thus greying out the "get from tablet" option. Also another error occurs:

> Error: TypeError: f.exists is not a function

Second, you cannot resend the file too. If you click on "send to tablet", ZotFile tells you that "1 of the selected attachments are already on the tablet. Do you want to replace these files on the tablet?". If you click "yes", it throws 3 errors. 2 of them regards the fact that the file does not exist. The third one is this:

> TypeError: tablet_file.exists is not a function (chrome://zotfile/content/zotfile.js, 2790)

Again, it should recover. It should say that the file was not found, probably the user deleted it, so he is going to send the file again without deleting the old file, as this old file does not exist. Instead it fails and the file is not sent

Strangely, the renaming fails too. It says that the item is top-level or the file does not exists. Maybe it tries to rename the tablet file too?

**Comment by jlegewie** [comment]
Yes, it should recover! Currently, a lot depends on good user behavior. E.g. also not a good idea to manually delete the tablet tag, or remove the info in the note. So yes, you are right. Might be a while before I get to it though...

**Comment by jlegewie** [comment]
This should be fixed in the master branch now. You can give it a try (Zotero 5 only)

**Comment by florianjehn** [comment]
I have encountered this problem today and I am using the most recent version of Zotfile and Zotero. Error message "File not found" keeps popping up after I deleted files on the tablet every time I use the Tablet Files searches. Any ideas how I can fix that?

**Comment by kirmaha** [comment]
I have the same issue. Several users are reporting this on Zotero forum : https://forums.zotero.org/discussion/86847/zotfile-tablet-file-tracking-problem

**Comment by florianjehn** [comment]
I could fix this for me by copying the files back on the tablet by hand (make sure filenames are exactly as before). This resolved the error messages and I could use Zotfile again with no problems.

**Comment by kirmaha** [comment]
Thank you for your comment. Not sure that it won't sound a bit stupid, but... I just figured that it works even without putting back a file with the exact same name. I just tried clicking "get file back from tablet" * without any other action : an error pops up (because the file I'm asking to get back does not exist), then the "get file back from tablet" option turns gray and the "_tablet" tag disappears. If I open the "Tablet" research folder, the error message "File not found" does not pop up anymore !

* not sure about the exact button label, as I use the French version

**Comment by countnegroni** [comment]
I'm having this same issue and it has basically broken my ability to use Zotfile to manage files on my tablet. Does anybody have a solution to this? It happens on all my computers so there must be something that's syncing to my library that causes Zotfile to look for these files, but I can't figure out what the heck it is so I can delete it.
