### ISSUE TITLE
Update to Zotero 5.0

### ISSUE THREAD

**Issue by sdaza** [jlegewie/zotfile#288]

**Comment by themeo** [comment]
Zotero 5.2 reports Zotfile is incompatible.

**Comment by sdaza** [comment]
Zotero 5.2? Where did you get that version? I have Zotero 5.0.1

**Comment by themeo** [comment]
Sorry, 5.0.2


12.07.2017 3:25 PM "Sebastian Daza" <notifications@github.com> napisał(a):

**Comment by jlegewie** [comment]
Zotfile 5.0 is now online. Just check www.zotfile.com
