### ISSUE TITLE
Tablet sync major problems

### ISSUE THREAD

**Issue by mtorax** [jlegewie/zotfile#292]
Using the tablet sync-function of zotfile 5 is resulting in two major errors:

1. the files aren't renamed correctly if using this option in the tablet settings. Instead of adding the defined suffix a $2 is added and the pdf suffix is removed. So the option to open the document easily is only possible by manually renaming the file.

1. the files aren't renamed correctly if using the "import from tablet" option. Instead of adding the expected ".pdf" file type after the defined suffix, a "$2" is added. So the option to open the document easily is only possible by manually renaming the file with the correct type.

**Comment by jlegewie** [comment]
I can reproduce this and will fix it probably within the next week maybe sooner. Note that this only happens with the "Save copy of annotated file with suffix" option. Without this option, everything works.

**Comment by jlegewie** [comment]
Should be fixed in the development version on GitHub. You can give it a try and let me know whether it works. Release version might still take a little.

**Comment by mtorax** [comment]
Works like a charme. Thanks for your fast change!
