### ISSUE TITLE
Numbers in text box partially hidden

### ISSUE THREAD

**Issue by srvanrell** [jlegewie/zotfile#294]
I've installed zotfile in Zotero 5.0.8. It is a fresh install since I've installed Ubuntu 16.04 a few days ago.

Some numbers are not completely shown. See _Maximum number of authors_ and _Number of authors to..._ in the snapshot below. I don't know if it is a Zotero or a zotfile bug.

![screenshot from 2017-08-09 21-37-52](https://user-images.githubusercontent.com/1920463/29149838-0812918c-7d4d-11e7-9ee3-e7a003ffd2ec.png)

**Comment by jlegewie** [comment]
Hard for me to fix this because I don't have an Ubuntu machine and the problem doesn't exist on macOS. So I just increased the size of the text boxes. Can you try the development version on GitHub and report back whether that helps?

**Comment by srvanrell** [comment]
Yes, I can try it in a few days. I'll let you know. Thank you

**Comment by srvanrell** [comment]
I think it is ok. Here it is a screenshot (using the github version)

![screenshot from 2017-08-14 11-45-43](https://user-images.githubusercontent.com/1920463/29276850-49040512-80e6-11e7-9332-585d83be35d4.png)

**Comment by srvanrell** [comment]
@jlegewie I've just realized that the last text box also hide "et al" last letter. You can see it in this thread images
