### ISSUE TITLE
PDF does not open in Skim

### ISSUE THREAD

**Issue by hanshuo** [jlegewie/zotfile#295]
System: Mac OS X El Capitan (10.11.6)
Zotero version: 5.0.12
Skim version: 1.4.29 

After setting the following options:

extensions.zotfile.pdfExtraction.openPdfMac -> "Skim"
extensions.zotfile.pdfExtraction.openPdfMac_skim -> true

Zotero still opens PDF files with Preview instead of Skim.

**Comment by jlegewie** [comment]
Works for me. Note that `openPdfMac_skim` is obsolete. `openPdfMac` -> "Skim" should do it. Can't do anything without the exact steps to reproduce...

**Comment by hanshuo** [comment]
1. Mac OS is set to open PDF with Preview by default. 
2. In Zotero, "extensions.zotfile.pdfExtraction.openPdfMac" is changed from "Preview" to "Skim". 
3. Double click any entry in Zotero with a PDF attachment still opens Preview instead of Skim.

**Comment by jlegewie** [comment]
Yes, that is expected. The option does not change how Zotero opens pdfs on double click. It only changes how zotfile opens links to pdfs in extracted annotations.
