### ISSUE TITLE
How to sync windows and mac?

### ISSUE THREAD

**Issue by ZLNjust** [jlegewie/zotfile#297]
RT 
I use the onedrive to sync the papers between Mac and Windows.
In windows, the zotfile renamed the paper name and linked address as 
> E:/onedrive/paper/storage/...

But in mac, the address is 
> /Users/.../OneDrive/paper/storage/...

so, the zotero can't find the attachment. 
So, how can I solve it?

**Comment by jlegewie** [comment]
Please use the Zotero forum for support question.
