### ISSUE TITLE
is there a method to mute the notification (after automatically renaming an attachment)? 

### ISSUE THREAD

**Issue by brahms2013** [jlegewie/zotfile#298]
is there a method to mute the notification (after automatically renaming an attachment)? 
Thank you.

**Comment by bwiernik** [comment]
In the config editor, set `extensions.zotfile.info_window_duration` and `extensions.zotfile.info_window_duration_clickable` to 0.

**Comment by jlegewie** [comment]
This is not a support forum... Please use the Zotero forum for support questions.

**Comment by jlegewie** [comment]
Thanks @bwiernik though...  :)

**Comment by brahms2013** [comment]
Thanks @bwiernik !
