### ISSUE TITLE
Articles are saved in undefined subfolder

### ISSUE THREAD

**Issue by Vital-Fernandez** [jlegewie/zotfile#300]
I set zotfile to organize my articles in a /author/ subfolder structure. However, I am having a /author/undefined/article structure. 

It is very similar to this issue which appears to be close:

https://github.com/jlegewie/zotfile/issues/268

I am using 5.0.17 zotero with 5.0.4 zotfile in ubuntu 5.0.4.

Thank you for your work

**Comment by jamy3531** [comment]
@jlegewie I met the issue, too. And I am using the Zotero 5.0.33 with the newest zotfile in Linux
