### ISSUE TITLE
Unsigned addon

### ISSUE THREAD

**Issue by ajustine** [jlegewie/zotfile#302]
Hello,
I am not able to install ZotFile because Firefox tells me that it is an unsigned addon. I already tried to install a Nightly and a Developer version of FF, but it still doesn't seem compatible with ZotFile.
Do you have any idea of what I should do to install it ?
Many thanks !
Justine

**Comment by jlegewie** [comment]
Please ask support question on the Zotero forum. Zotfile 5 doesn't work with FF (only Zotero Standalone 5)
