### ISSUE TITLE
Add tag(s) wildcards for file renaming

### ISSUE THREAD

**Issue by hora** [jlegewie/zotfile#304]
This may be a duplicate of #113, but I'm not interested in renaming folders, rather the files themselves.

What I would like is to allow renaming files using all the tags associated with them in Zotero. For example if I have the tags "education" and "sociology", I could add them to the name of the files like so:

> Last, First (yyyy) - Title [education, sociology]

I could open a PR for this – my question being, should this be possible? I don't see tags in the Zotero field types API...

**Comment by jlegewie** [comment]
Yeah, possible but I am a little reluctant. Don't really see the general use and I don't have  much time for testing etc right now. So you could do a pull request but it would take a while before I get to it...

**Comment by hora** [comment]
No problem, I understand. The reason I wanted this was to facilitate working with attached PDFs from the command line, but I've found another workflow that works for me.

**Comment by hora** [comment]
Hello @freemooshee,

I'm no longer using tags in file names, it was proving too cumbersome. But I did write a little fish script that searches for tags and adds them. It's not well-tested at all, nor is it versatile. But if it can help you, here it is: https://gist.github.com/hora/d01bfc322c95f16617a567deef1a3847

**Comment by freemooshee** [comment]
Hello @hora,

thanks for your help! This at least automates renaming of Zotero attachments, now I only need to find a way to get the tags set in Zotero UI...
