### ISSUE TITLE
Zotfile not automatically detecting files

### ISSUE THREAD

**Issue by alphe1** [jlegewie/zotfile#308]
Mac osX High Sierra (10.13)
Zotero v. 5.0.21
Zotfile v.5.0.4

1. Zotfile does not detect new files in Source Folder and thus does not add the document as a new attachment to the selected entry.
 - I have tried changing the location of the source folder as well as uninstalling/reinstalling Zotfile

2. Zotfile dialogue box after manually adding attachment does not disappear unless clicked.

**Comment by jlegewie** [comment]
1. Zotfile 5 doesn’t automatically detect PDFs in the watch folder anymore. See change log 

2. That is a known issue
