### ISSUE TITLE
"Attachments skipped" error

### ISSUE THREAD

**Issue by jeanluct** [jlegewie/zotfile#309]
Hi all,

I've been happily using ZotFiles for several years.  Yesterday I wanted to export all the PDFs in a subcollection so I turned on the "tablet" mode.  I exported the PDFs to a folder, worked like a charm.  Then I turned off the tablet feature since I don't really need it.

Now I can't rename any PDFs.  Whenever I try to do so with the right-click context menu, I get the error:

"Attachments skipped because they are top-level items, snapshots or the file does not exist."

But the file does exist... if I double-click I get the PDF, as expected.  It's an attachment, and not a snapshot.

Any idea what might be going on?

Thanks,

JLT

**Comment by jlegewie** [comment]
Please use the zotero forum for support questions. The problem is that you should not have used the tablet functionality and instead just used a custom location for renaming. But please post your question on the zotero forum.
