### ISSUE TITLE
Suggestion: copy correct filename to clipboard

### ISSUE THREAD

**Issue by chappy721** [jlegewie/zotfile#311]
Hello
I've been working with Zotfile for a while and I find it very useful. Thanks for it!

Very often I work with PDF-files outside of Zotero (in a Dropbox structure). One great function for me would be, that I could select an entry in Zotero and with a click or a shortcut, the correct filename will be copied to the clipboard.

So it would be very easy to rename the PDFs outside Zotero very easily.
Or is there already a function like this? I was not able to find it.

Thanks a lot!
Daniel

**Comment by bwiernik** [comment]
You should generally never rename files outside of Zotero. This will almost certainly lead to Zotero being unable to locate files. To rename a file, either use Zotfile's rename feature, Zotero's rename feature, or click on the attach file name (in bold) in the right pane in Zotero when you have the attachment item selected.

**Comment by chappy721** [comment]
thanks. Yes I know, but I don't work this way. Normally I do not attach PDFs in Zotero because I have my own structure outside Zotero, somewhere in Dropbox. I'm a bit afraid of storing PDFs in the Zotero folder. With Dropbox I'm sure it's working. But yes, perhaps I should change my mind;-).

**Comment by bwiernik** [comment]
Zotfile can automatically generate a file structure in Dropbox. It (and Zotero natively) can also rename linked attachments in place without moving them. Maintaining a library of PDFs separately outside of Zotero misses half of the convenience and functionality of the program.

**Comment by chappy721** [comment]
perfect tipp, thanks a lot! Changed my system. It's much more comfortable now:-).
