### ISSUE TITLE
Cannot run zotfile on firefox b/c is unsigned

### ISSUE THREAD

**Issue by ncastagno** [jlegewie/zotfile#312]
Dear all - I cannot install zotfile on my Firefox (48) because the system tells me that the add on is unverified (unsigned).  Can you please sign the add on?

Thanks!
Niccolò

**Comment by jlegewie** [comment]
Similar to Zotero 5, Zotfile 5 doesn't work with Firefox.... Zotfile 5 is only only for Zotero standalone.
