### ISSUE TITLE
How can I make zotfile sync local files when specifying a new pdf folder?

### ISSUE THREAD

**Issue by amosbird** [jlegewie/zotfile#314]
Hi, I just installed zotfile and specified a new folder which stores my downloaded pdf files.

![image](https://user-images.githubusercontent.com/5085485/32269841-999c96c4-bec1-11e7-809a-8fcceec657e0.png)

However I cannot find an action to bring them into zotero. I tried `sync` but it doesn't do anything.

**Comment by jlegewie** [comment]
Please post support questions on the Zotero forum...
