### ISSUE TITLE
Source folder for attaching new files and working with annotations

### ISSUE THREAD

**Issue by Taufiq-Hail** [jlegewie/zotfile#315]
When trying to activate the option of source folder for attaching new files, it appears it does not respond and Zotero 5.0 does not recognize the settings. Kindly make the proper amendments to it.
Second thing, when trying to use the number list in the annotation word processing pane, the change of numbers or the automatic increasing/decreasing does not work. Kindly fix the bug.

**Comment by jlegewie** [comment]
Please provide exact steps to reproduce the bug. IF this is a support question and not a bug report, please post it on the Zotero forum and not here on GitHub.
