### ISSUE TITLE
Attach New File not working

### ISSUE THREAD

**Issue by martinmts** [jlegewie/zotfile#317]
Hello,
When I click "Attach New File", Zotero does nothing.
I've tried to reinstall Zotfile, but it was good only for a while. Then the problem came back.
When this happens, Zotfile Preference from the Menu bar will not work either.
I will have to go to "Add-ons" first and from there click the Preference button.

I disabled the add-on, restart, then enable it, restart. It is working for now. And now clicking on "Zotfile Preference" from the Menu bar also works. These two seem to be connected.
Thanks!
Martin

**Comment by jlegewie** [comment]
See "Reporting a bug" (http://zotfile.com/#reporting-a-bug)...
