### ISSUE TITLE
Clarify installation instructions

### ISSUE THREAD

**Issue by dstillman** [jlegewie/zotfile#324]
We're getting tons of posts in the Zotero Forums from people trying to install ZotFile into Firefox (or just clicking the download link in Firefox rather than using Save As or dragging the link to the Zotero Add-ons window).

https://forums.zotero.org/discussion/comment/292302/#Comment_292302
https://forums.zotero.org/discussion/comment/293465/#Comment_293465
https://forums.zotero.org/discussion/comment/293981/#Comment_293981
https://forums.zotero.org/discussion/comment/294009/#Comment_294009
https://forums.zotero.org/discussion/69153/zotfile-plugin-not-allowed

It would be good to clarify this near the Download link on zotfile.com. (It would probably also be much easier for people if the download link just fetched the latest file (maybe automatically with a little script) instead of sending them to the GitHub releases page.)

The AMO page can probably also be removed at this point.

**Comment by jlegewie** [comment]
Will do.

One question: Do you know a user-friendly solution to download xpi files on Firefox 57? It's pretty annoying. Take the example here: https://github.com/jlegewie/zotfile/releases/tag/v5.0.6
Clicking on the link for the xpi file triggers the "FF prevented the site from installing addon" dialog. Right-click works but that is not user-friendly for a "Download" button on the zotfile webpage at all.

**Comment by dstillman** [comment]
Dragging the XPI link directly to the Zotero Add-ons pane works, but you can actually give it any extension and Zotero will still install it, while preventing GitHub from serving it as `application/x-xpinstall` and therefore Firefox from trying to install it.

We should actually probably pick a new file extension for Zotero plugins, which we can even start registering for with the OS so they can be installed via double-click. Maybe just `.zoteroplugin`? (Safari uses `.safariext`.)

(The connector could also listen for a particular Content-Type and send the file to Zotero if open, but that wouldn't work from GitHub. We could probably use the [downloads API](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/downloads) with the filename extension, though.)

/cc @retorquere, @fbennett, @willsALMANJ, @bwiernik

**Comment by jlegewie** [comment]
Double click support with an zotero-specific extension like `.zoteroplugin` would be great! So much easier for the user.

I just updated the website to skip the github step (+ plus a popup on FF with instructions to use right-click for download). I still have to add instructions to install in Zotero though but that would be obsolete with `.zoteroplugin`.

**Comment by jlegewie** [comment]
I added another link to the instructions directly below the download button...

Still a zotero-specific extension for plugins would make it much easier for users...
