### ISSUE TITLE
Feature request: Rename pdf to (BetterBibtex) citekey

### ISSUE THREAD

**Issue by stevebarratt123** [jlegewie/zotfile#327]
It would be cool if I could get zotfile to automatically rename pdfs to match the citekey generated for the entry by BetterBibtex (https://github.com/retorquere/zotero-better-bibtex). Eg: Citekey Bloggs1999  matches Bloggs1999.pdf.

This would be very useful because when authoring a document using latex (/markdown etc) all the references appear in text using these citekeys. Quickly typing the first letters of a citekey in a system search tool (eg OSX spotlight search, GNOME activities search etc) will promptly reveal the file to open, often in less than 5 keystrokes from the point of text entry of the document. 

I have sort of worked around the need by matching the naming format between the same extensions, but when I have something let Bloggs1999a as a citekey, zotfile still renames to Bloggs1999.pdf

**Comment by jlegewie** [comment]
Does this solve your problem?

https://github.com/retorquere/zotero-better-bibtex/issues/768#issuecomment-342271291

In any case, there is an exciting Issue for this to please close this and comment there. In any case, I would be interested to hear whether the link above addresses your questions.

**Comment by stevebarratt123** [comment]
seems fair enough, apologies for the delay - closing now
