### ISSUE TITLE
"Undefined" folder from %c wildcard

### ISSUE THREAD

**Issue by dventuri** [jlegewie/zotfile#331]
Hi, 

using the %c (collection) wildcard for the location of files for storage is creating a folder with the name "undefined" before the folder with the name of the collection itself. Using ZotFile 5.0.6.

I saw that this should have been fixed in version 5.0.3.

**Comment by quigui** [comment]
The issue is also unresolved on ZotFile 5.0.7.

**Comment by Bercio** [comment]
Same here, using a combination (%c/Lib) creates an undefined parent directory, %c alone works fine
