### ISSUE TITLE
No Signing certificate of extension for Firefox 48

### ISSUE THREAD

**Issue by Robou** [jlegewie/zotfile#336]
Since Firefox 48, Release and Beta versions of Firefox for Desktop **will not allow unsigned extensions to be installed**, with no possible override of this  limitation. It's thus only possible to install ZotFile using Firefox **Developper Edition** or **Nightly Edition**

-> Could any one follow the Extension Signing process in order to allow Firefox users install ZotFile please?

see [https://wiki.mozilla.org/Add-ons/Extension_Signing](https://wiki.mozilla.org/Add-ons/Extension_Signing) for the process.
Thanks in advance !

**Comment by jlegewie** [comment]
Zotfile 5 is not a Firefox add-on (only Zotero Standalone)...  So no Firefox signing.
