### ISSUE TITLE
can zotfile be setup to automatically extract notes upon saving a pdf?

### ISSUE THREAD

**Issue by ramiroricardo** [jlegewie/zotfile#337]
Dear all,

Not sure this is the right place for this sort of questiong, but I am just moving to use zotero+zotfile and I was wondering if it is possible to set up zotfile to automatically extract the notes into zotero, after saving a pdf? (i.e. without having to manually go to "extract annotations").

Thanks,

Ramiro

**Comment by jlegewie** [comment]
Nope that is not possible right now and you can select all zotero items and go to extract annotations (or so 10, 20 or whatever at a time). Otherwise please ask support questions on the Zotero forum and not here on github. Thanks.
