### ISSUE TITLE
Adding new documents from the tablet

### ISSUE THREAD

**Issue by rpgoldman** [jlegewie/zotfile#338]
I am able to send files to my tablet with zotfile by putting them in a distinguished folder on Google Drive.  Is there some way to enable transfer the other way, as well?  I.e., while reading on my tablet, I found a related new pdf that I would like to add to zotero.  So I saved it into that same directory in Google Drive.  However, Zotfile does not seem to see this new file.

Is this simply not possible (and should I be doing this a different way?) or is there something I can do to notify Zotfile to check the synchronizing folder for new pdfs?

Thanks

**Comment by jlegewie** [comment]
You can set that folder as your Zotfile source folder. Otherwise, nope.
