### ISSUE TITLE
Broken: Zotfile on Zotero Standalone 5.0.35.1

### ISSUE THREAD

**Issue by bernhardre** [jlegewie/zotfile#339]
Since I've updated my windows zotero standalone to version 5.0.35.1 zotfile doesn't work anymore.
It says that it's not compatible with this version. Any chance to fix this?

Zotfile is was what makes Zotero useful to me (automatic note extraction, easy transfer to a tablet, proper renaming of files). Thanks for the great work!

**Comment by jlegewie** [comment]
It is. Just google and install zotfile 5
