### ISSUE TITLE
ZotFile rename and Attaching new files do not work after Zotero 5.0.36

### ISSUE THREAD

**Issue by liuyun16** [jlegewie/zotfile#343]
Hello, 
These two days, Zotero have automatically updated to 5.0.36, which can  now automatically renames PDFs based on the parent metadata by Zotero itself. 
I prefer the best ZotFile add-on. So I have disable the Zotero renaming function.
But what I found is that the Zotfile could not work properly again. The problems are as follows:
1,  When I add new PDF in the website, the Zotfile could not rename the attachment automatically, and also coul dnot move the new added  attachments to my customized location;
2. During this failed process, the Zotfile give the the dialog box as follows : 
![](https://farm5.staticflickr.com/4774/39892031075_9303ba1d33_o.png)

And it always suspend on the screen until  I click it. 

So I think this may come from the Zotero update. Can anyone fix it ??
Thanks!

**Comment by jlegewie** [comment]
Works for me with Zotero 5.0.36 and zotfile 5.0.7...  I can only look into it with a reproducible example.

**Comment by liuyun16** [comment]
Thanks for your reply. 
I also use Zotero 5.0.36 and zotfile 5.0.7, but I really don't understand how do the problem come from...
I also reinstall the zotfile add-on, but it did not help. 
So any suggestions?
