### ISSUE TITLE
Move, rename and attach to zotero item multiple files

### ISSUE THREAD

**Issue by pprw** [jlegewie/zotfile#345]
I use zotfile to attach a document I just downloaded to a zotero entry. With my configuration, zotfile will move the document to a specific folder and rename it.

It works well when I download something from firefox. Zotfile will look for the last modified document in my download folder and attach this file. But if a friend give me a usb stick with plenty of pdfs, I have no way to attach them to my zotero entries. 

How can I proceed in this case?

**Comment by jlegewie** [comment]
Please use the Zotero forum for support questions about zotfile. Github is for bug reports etc. Thanks!
