### ISSUE TITLE
Question: How to extract annotations on the terminal?

### ISSUE THREAD

**Issue by vonpupp** [jlegewie/zotfile#346]
Hello,

My question might be a bit weird but I am looking forward to be able to extract annotations directly via the CLI. Something like `python extractannotations.py <file.pdf>`. The problem seems that the poppler bindings do not get the content of the annotations, eventhough seems to recognize that an anotation exists on that page. See [this example] and this [another example].

Would you have any recommendation or could you point me into the right direction on how to do so? Even when it is not in python but if I can run it on the CLI it would be amazing.

Thank you very much.

[this example]: https://gist.github.com/compleatang/8666561
[another example]: https://gist.github.com/stevepowell99/e1e389a57ea9a2bcb988

**Comment by jlegewie** [comment]
I am not aware of any simple solution. My knowledge might be a little outdated but when I looked around, there were very few solutions that extract annotation text from PDFs (hightlighted text, not just notes). There is still the poppler implementation in zotfile but that is very old, was never compiled for anything else than macOS and I can’t provide any other support for it. So it would require some work but if you are comfortable with c, it might be an option. Another option would be to create a Node.js module from the zerfiel PDF.js-based solution so you could call it from the command line (and therefore python) but again I won’t do it and provide a lot of support.

**Comment by vonpupp** [comment]
Thank for the answer. Yes, PDF highlighting extraction seems to be quite a mess, and poppler doesn't seem to work properly for me (using python). It doesn't worth for me going into C for this, I rather import it into Zotero and export annotations manually using zotfile.

What exactly do you mean by zerfiel PDF.js based solution? Could you please post the link?

Thanks.

**Comment by jlegewie** [comment]
https://github.com/jlegewie/zotfile/tree/master/chrome/content/zotfile/pdfextract
