### ISSUE TITLE
Renaming file: use ascii only and no quotes

### ISSUE THREAD

**Issue by melsophos** [jlegewie/zotfile#349]
I really like the renaming feature of Zotfile, this is very useful! I think that two additional options could be very useful beside the existing ones:

- use only ascii character (so replace ä → a, é → e, etc.);
- removes simple and double quotes.

The main motivation for both is to manipulate path in Bash, FTP script, MTP transfer, etc.

**Comment by jlegewie** [comment]
You should be able to do that with user defined wildcards. see here: http://zotfile.com/#user-defined-wildcards
