### ISSUE TITLE
Scan for multiple files after renaming folder

### ISSUE THREAD

**Issue by kaktux** [jlegewie/zotfile#351]
hi there,

i renamed a folder which contains subfolders (and so on) - and one of these is the folder i have my pdf attachments for zotero stored (moved there with zotfile).
So basically i did something like renaming
/home/oldname/x/y//z/zoteropdfs
to
/home/newname/x/y//z/zoteropdfs

After that i changed the file path in zotero/zotfile settings to the new one.
But now whenever i want to open a pdf from zotero it says "i can't find the attached file" - and i have to browse to the folder by hand.

So probably i did something wrong in the procedure - but now its done. Also tbh (and first thing i tried) was renaming the folder backwards - but im not 100% sure what the old name was (capitalisation and all) - didnt work.

Is there a way to tell zotfile in which directory it should watch for the files that cant be found? A more or less simple - "hey- check that directory for all attachments in the library and change your currently saved location to that"??

**Comment by jlegewie** [comment]
Please use the Zotero forum for support questions. This is also not really anything that is specific to Zotfile...

**Comment by kaktux** [comment]
ok - thx - thought this is zotfile related
