### ISSUE TITLE
Zotero and Okular - zotfile.pdfExtraction.openPdfLinux Not working

### ISSUE THREAD

**Issue by LordAmit** [jlegewie/zotfile#353]
Hello,
based on Instructions I have used `/usr/bin/okular -p` as value for the `zotfile.pdfExtraction.openPdfLinux `config. However, now when I click on `open link`, it does nothing. Opening Zotero from Console shows the following message: 
```
Possibly unhandled rejection:

Component returned failure code: 0x80520006 (NS_ERROR_FILE_TARGET_DOES_NOT_EXIST) [nsILocalFile.isExecutable]

[Exception... "Component returned failure code: 0x80520006 (NS_ERROR_FILE_TARGET_DOES_NOT_EXIST) [nsILocalFile.isExecutable]"  nsresult: "0x80520006 (NS_ERROR_FILE_TARGET_DOES_NOT_EXIST)"  location: "JS frame :: chrome://zotero/content/xpcom/utilities_internal.js :: Zotero.Utilities.Internal.exec< :: line 501"  data: no]
    Zotero.Utilities.Internal.exec<@chrome://zotero/content/xpcom/utilities_internal.js:501:8
From previous event:
    ZoteroPane</this.loadURI@chrome://zotero/content/zoteroPane.js:3331:7
    set_mode/this._eventHandler<@chrome://zotero/content/bindings/styled-textbox.xml:447:11
    .init_instance_callback/</<@resource://zotero/tinymce/note.html?locale=en-US&dir=ltr:172:6
    Dm/<.addCommand/i.exec[t]@resource://zotero/tinymce/tinymce.min.js:2:182339
    Dm/<.execCommand@resource://zotero/tinymce/tinymce.min.js:2:181480
    mC.prototype.execCommand@resource://zotero/tinymce/tinymce.min.js:2:326250
    $@resource://zotero/tinymce/plugins/link/plugin.min.js:1:7039
    G/<@resource://zotero/tinymce/plugins/link/plugin.min.js:1:7165
    Pm/r.fire@resource://zotero/tinymce/tinymce.min.js:2:188686
    nt.fire@resource://zotero/tinymce/themes/modern/theme.min.js:1:30475
    a@resource://zotero/tinymce/themes/modern/theme.min.js:1:34690
    ke/u@resource://zotero/tinymce/tinymce.min.js:2:11679
    ke/i.bind/C@resource://zotero/tinymce/tinymce.min.js:2:11830
```

I am using Linux Mint 18.3, 64 bit edition Cinnamon. I have okular installed, and Zotero+Zotfile updated till last night.

**Comment by LordAmit** [comment]
Hello,
Any update?

**Comment by TaipanRex** [comment]
Same problem for me. Tried with zathura.

**Comment by bpiwowar** [comment]
Given the source code, you should pass

`/usr/bin/okular-p`

without space this is because zutilo split the string around the `-`, and if there is only one `-`, then the executable has an extra space at the end. I guess if somebody wants to fix this would be to have a template with two syntaxes, e.g. `/usr/bin/okular @FILE; /usr/bin/okular -p @PATH @FILE`.

**Comment by TaipanRex** [comment]
@bpiwowar that worked perfectly, thanks. For zathura, I added `/bin/zathura-P`. Note you need the full path.

**Comment by kirk86** [comment]
@jlegewie I'm still facing this issue using the suggested solutions, (i.e.) `/usr/bin/qpdfview-p` does open the pdf but it results in errors initially saying couldn't open the `-` dash symbol, I guess somehow it looks at it as a file, and the other error is that it can't open specific section from your annotations, if you click on the link of the annotation it says couldn't find file `-` dash and then couldn't open section `X`, (e.g.) 25. After those two errors it opens the pdf but not at the correct section where the annotation is.

I've tried multiple variations of this `/usr/bin/qpdfview -p` with/without space, capital/non capital `p` single/double `-` dash, but nothing has worked properly, has anyone figured a solution that actually opens the pdf correctly at the section or where the annotation was inserted?
