### ISSUE TITLE
zotfile fail to watch source folder

### ISSUE THREAD

**Issue by scutzck033** [jlegewie/zotfile#354]
Hello! I am using **win10** and the zotero version is **5.0**. I use the plugin zotfile and everything is good except **zotfile failing to look for the most recently modified file in the source folder!** So I have to drag the downloaded pdf files into zotero manually, which is not that convenient. Hope you can give me a solution. Thanks!

**Comment by jlegewie** [comment]
This feature was removed. Look at the change log and please use the zoetrope forum for support questions.
