### ISSUE TITLE
pop-up notes are extracted but not the inline notes

### ISSUE THREAD

**Issue by lopippo** [jlegewie/zotfile#356]
Greetings,

I use zotfile happily along with okular, the pdf viewing/annotating program. There are different kinds of annotations, like pop-up notes that show in the document with an icon and inline notes that show in the document as rectangles containing the text of the note. I like this latest kind of annotation a lot. Unfortunately, this kind of note is not extracted (anymore, as it used to be). 

I attach a test file.

Thank you for your kind attention,
lopippo
[morgner-robinson-massign-assign-peaks-assemblies-native-ms-analchem-2012.pdf](https://github.com/jlegewie/zotfile/files/2097253/morgner-robinson-massign-assign-peaks-assemblies-native-ms-analchem-2012.pdf)

http://msxpertsuite.org

**Comment by jlegewie** [comment]
Zotfile never extracted in-line notes and there are currently no plans to do so.

**Comment by lopippo** [comment]
Ah! so that means that my rememberings are incorrect. Maybe I used another tool to do that. Why do you say that you do not have plans ? Because it is (difficult | time consuming) or because this is not a valid use case ?
Sincerely,
lopippo
