### ISSUE TITLE
Zotero not acting automatically (no automatic move/renaming)

### ISSUE THREAD

**Issue by tkietzma** [jlegewie/zotfile#357]
Dear developers,

First of all, thanks for providing zotfile, which is the perfect addition to Zotero. It works exactly as expected, with the exception of one bit: it does not seem to automatically kick into action for me. That is, if I drag/drop a PDF into the library, an entry is successfully created, but the PDF is stored in the zotero/storage folder. To get zotfile to move and rename the PDF, I need to manually activate it via "manage attachments -> rename attachments".

I am using Zotero 5.0.51 (MAC) with zotfile 5.0.8. 

I have tried a lot of things, but no avail. I have turned full-text and file synching on and off, I have tried working with a relative or absolute base directory, I have unlinked my account from Zotero. I have tried adding PDFs per drag/drop, but also via browser extension. Today, I have deleted the whole library and started with a fresh install. Still, it will not automatically rename.

Would you be able to point me in the right direction, or tell me where I go wrong?

Thanks a lot!
Tim

**Comment by jlegewie** [comment]
Glad that you enjoy zotfile. Please use the Zotero forum for support question (and look at existing issues here https://github.com/jlegewie/zotfile/issues/283)

**Comment by tkietzma** [comment]
Thanks for your response and the pointer to the other issue. If I see correctly from #283, what I expected to happen is not actually supported by zotfile in the first place (use case 4 below):

> 1. Add item to zotero using Zotero Connector (e.g. in FF). Automatic renaming works.
> 2. Drag and drop one pdf on existing zotero item. Automatic renaming works.
> 3. Drag and drop multiple pdfs on existing zotero item. Some problems
> 4. Drag and drop pdf on Zotero (not existing item), Zotero will retrieve the metadata and create a parent item. Automatic does not work.

I just tried case 1, and zotfile works as expected.

**Comment by kongdd** [comment]
How about situation 3 and 4, it also not work for me.
