### ISSUE TITLE
Multiple linked attachments receive same name in Zotero

### ISSUE THREAD

**Issue by mcv100** [jlegewie/zotfile#358]
I have set up automatic renaming and moving with Zotfile in Zotero. A problem arises when adding multiple attachments to a Zotero entry.

**Expected behavior**
If the first attachment was named name.pdf, the second should be named name2.pdf, also within Zotero so that the files are treated separately.

**Problem**
The actual files are indeed (moved and) renamed name.pdf and name2.pdf, however both entries in Zotero will now be linked to the same name.pdf file. Both the attachment titles as well as the filenames within Zotero refer to this same name.pdf file. Trying to rename either one of the attachments manually will result in name.pdf being renamed on disk. There is no link to name2.pdf anymore. The only way to get name2.pdf as an attachment again is to re-add it in Zotero.

I'm using Zotero 5.0.52 with Zotfile 5.0.8 on Windows 10. I'm currently circumventing this problem by having the option "Add user input to filename" enabled, so I can manually set different filenames for multiple attachments.

(could possibly be related to #320)

**Comment by masteranza** [comment]
I have the same problem - if we could only have an optional, say {%m} wildcard which would enumerate whenever multiple pdf's are attached.

**Comment by jooh** [comment]
Same problem here. Using OS X, Zotero 5.0.56, Zotfile 5.0.8.

**Comment by masteranza** [comment]
So is there a way to have a custom renaming rule that will enumerate the files?
If I have one file say 'someone2017title' and then another file, can this another file be renamed to 'someone2017title2'?

**Comment by watercrossing** [comment]
I would create a separate issue requesting a custom renaming rule. 
The `someone2017title2.pdf` renaming is what is currently happening (and `someone2017title3.pdf` etc for subsequent attachments.

**Comment by masteranza** [comment]
Wait, currently happening? I guess that you mean when I don't have a custom renaming rule, right?

**Comment by watercrossing** [comment]
Regardless of your renaming rule, if a file with the target filename already exists, the new file will have a number appended to it which gets incremented until the filename is available (or the number is > 999). 
(And by currently happening I mean since yesterday, and I am not sure Joscha has released an updated version yet.)

**Comment by jlegewie** [comment]
I will publish the version probably this weekend. I was already supposed to work like this before but there was a bug... Thanks to @watercrossing, it's now fixed.

**Comment by masteranza** [comment]
@watercrossing @jlegewie thank you!
