### ISSUE TITLE
Installation in firefox for zotero 5 says .xpi file is corrupt

### ISSUE THREAD

**Issue by SwastikM** [jlegewie/zotfile#361]
"The add-on downloaded from this site could not be installed because it appears to be corrupt", is the message I get every time I try to download and install the .xpi file at https://addons.mozilla.org/firefox/downloads/file/585224/zotfile-4.2.8-fx.xpi?src=dp-btn-primary. 

I also downloaded the github repo, created the .xpi file by putting all the files at the top level. Then I tried installing it in firefox, but I still get the same error.

**Comment by jlegewie** [comment]
Yeah, download from zotfile.com and follow the instructions there. You have to install zotfile in Zotero NOT firefox.

And please don't use github for support questions.
