### ISSUE TITLE
ZotFile Rename Attachments only processes first item in selection

### ISSUE THREAD

**Issue by byronwall** [jlegewie/zotfile#366]
I have just imported a Mendeley library using the stock Zotero feature.  It brought them in as linked attachments instead of storing the file in my Zotero storage.  I saw online that the ZotFile rename could add the linked file to my Zotero storage and then rename.  I don't actually care about the file name, but I do want to bulk add these files to my Zotero storage instead of keeping the linked attachment.

When using `Manage Attachments -> Rename Attachments` off the context menu, I click OK to `Do you want to rename 777 attachments?`.  At that point, only the first item is processed.  Zotero retains the selection from before.

Same thing happens with 2 or 777 attachments.

I can provide a debug log or better information with a pointer or two about what info is needed.  Thanks!

**Comment by byronwall** [comment]
To be clear, this happens whether the parent item has a single linked attachment or if there are additional items like notes.  It always seems to process the first item correctly, but then stops after that.  If I tell it to go again, it will skip through the previously completed items and then process only the first "new" item.  That is, the first item which is currently a linked attachment instead of a stored-in-Zotero attachment.

**Comment by jlegewie** [comment]
http://zotfile.com/#reporting-a-bug

**Comment by jlegewie** [comment]
You can just post here if this is a bug with clear info. Pretty unclear when I will get to it though.

**Comment by byronwall** [comment]
I ended up processing them manually with some help from AutoHotKey.
