### ISSUE TITLE
Rename Attachements on multiple selected items does NOT work

### ISSUE THREAD

**Issue by 01baftb** [jlegewie/zotfile#368]
I am trying to use ZotFile to convert batch convert multiple items from "Link to file" into "Stored copy" that is manged by Zotero internally. 

I selected multple items (batch) and then did the following:  _**Right click >> Management Attachments >> Rename Attachments**_.  This action resulting in the following two issues: 

1) Only the first item of the batch multiple selected items gets renamed. The PDF of the first item got renamed and moved. All other items didn't get renamed and moved.  

2) ZotFile actually renames and moves the "original" file that was linked. This is BAD! Original files in the link should never be moved from the original location. 

ZotFile v5.0.8
Zotero v5.0.55

**Comment by pietau** [comment]
I have exactly the same problem:
ZotFile v5.0.9
Zotero 5.0.61

**Comment by 01baftb** [comment]
Although this issue is related to ZotFile, Zotero team has a planned feature for converting linked files into copy of files. Therefore, if you're trying to use ZotFile to convert linked files into copy of files, then you may be able to do so natively in Zotero soon: https://github.com/zotero/zotero/issues/1637

**Comment by dstillman** [comment]
I've just pushed out a new <a href="https://www.zotero.org/support/dev_builds">Zotero beta</a> that includes this feature as File → Manage Attachments → "Convert Linked Files to Stored Files…".

https://forums.zotero.org/discussion/comment/338094/#Comment_338094

**Comment by dstillman** [comment]
I [submitted a patch](https://github.com/jlegewie/zotfile/pull/431) for various possible errors when renaming multiple files, and those fixes are now in ZotFile 5.0.13, so this can probably be closed.
