### ISSUE TITLE
Updated to macOS Mojave and highlights/annotations to pdf are not rendered in zotfile at all

### ISSUE THREAD

**Issue by edouerd** [jlegewie/zotfile#372]
Hello, writing an issue to make note that zotfile appears to not function (at all) on the latest release of macOS. This may be an OS-specific bug, since I can't appear to highlight pdf text at all with my mouse (on click + drag), but highlights made using the annotation tools render fine.

Can provide additional details/context if needed!

**Comment by jlegewie** [comment]
Zotfile doesn't highlight pdf text. It only extract annotation done with a different app...

**Comment by edouerd** [comment]
That's what I mean — I'm not asking for Zotfile to highlight anything for me — I'm saying when I highlight/annotate text in Preview (the default macOS pdf app), those highlights/annotations seem to not be extracted into Zotfile. This is my main issue.

**Comment by jlegewie** [comment]
I just tried on macOS Mojave and I can extract annotations the same way as before...
So this seems to be unrelated to Mojave.
