### ISSUE TITLE
[question] how to change hyphened words into unserscored words

### ISSUE THREAD

**Issue by kirk86** [jlegewie/zotfile#373]
Hi @jlegewie,
thank you for creating zotfile and sharing it with us.
I was going through the documentation of wildcards and I couldn't found how to change the rename of a file from:
![image](https://user-images.githubusercontent.com/2902390/47042492-e8fe5f00-d17a-11e8-81f4-9c81d657fc0e.png)

to author_year_shorttitle, where short title should be lowercase and anything between words should be replaced by an underscore. 

In the above example `polynomial-time` appears as is in the title of the pdf how can we what wildcard should we use to transform such things into `polynomial_time`?

A second question that I stumble upon is how to use the wildcards so that it will create automatic subfolders based on authors first letter of last name/year/author/title.

Something like the above is possible via `bibdesk` or `jabref` but not sure how to achieve it using `zotfile` + `zotero`?

**Comment by jlegewie** [comment]
Please use the Zotero forum for support question.

**Comment by kirk86** [comment]
@jlegewie thank you, apologies, didn't know. 
Closing issue.
