### ISSUE TITLE
Error:the add-on is broken

### ISSUE THREAD

**Issue by Lolipa** [jlegewie/zotfile#398]
dowloading '.xpi' file of the latest version of Zotfile, after finishing Firefox reminds me that the attachment is broken and can not be installed. Other versions were tried, but failed with the same reason. What can I do?

**Comment by adam3smith** [comment]
The add-on is fine. Re-read the install instructions. ZotFile is a Zotero add-on, not a Firefox add-on. You would download the .xpi file (right-click --> save link as in Firefox, e.g.) and then install it from the Tools--> add-ons menu in Zotero.
