### ISSUE TITLE
Option to fix Windows-incompatible filenames

### ISSUE THREAD

**Issue by cpence** [jlegewie/zotfile#403]
Hello! I sync my Zotero folder via Dropbox to both Windows and Linux machines, and would love an option that would allow me to remove windows-incompatible filename characters -- in particular, dots at the end of filenames (common if you have folders named after publishing companies ending in "Co.") and question marks. Is there a way to add such a setting, or patch around it myself?

**Comment by jlegewie** [comment]
You should be able to do it with custom wildcards: http://zotfile.com/#user-defined-wildcards
But I can’t provide individual support for it.
