### ISSUE TITLE
Feature request: delete attached files from zotfile Custom Location

### ISSUE THREAD

**Issue by hchuanqi** [jlegewie/zotfile#404]
Hello,

I'm a new user of Zotero as well as zotfile. Firstly, I will thank everybody here for building the excellent tools. 

Currently the command 'Move Item to trash' and 'empty the trash' on attached pdf files stored in **zotfile Custom Location** only remove the reference of the file, so it leaves the pdf files **on my disk** and **unassociated to any item**. 

The above commands executes as expected to remove files from disk when attached files are stored in **Zotero's defaut location**. I have searched through Zotero forum, and it said that the unexpected behavior described above is up to zotfile, see [Deleting Files With Item](https://forums.zotero.org/discussion/33975/deleting-files-with-item).

The problem has made some confusion (on Zotero forum and this repo) over years even recently.
[Deleting Files With Item](https://forums.zotero.org/discussion/33975/deleting-files-with-item). 
[Ways to detect and delete unassociated pdf's in my storage folder?](https://forums.zotero.org/discussion/77166/ways-to-detect-and-delete-unassociated-pdfs-in-my-storage-folder). -- 14 days ago, but not by me!
[When I delete items in trash, the file in this item do not delete]()
[Doesn't delete file in zotero and in folder once it has been renamed (moved)](https://github.com/jlegewie/zotfile/issues/269)
[Delete attachment in file system when item is deleted in zotero](https://github.com/jlegewie/zotfile/issues/214)

Here I ask for a help that someone can add a feature to let it possible to remove certain files from zotfile Custom Location when it is needed.

Thank you all very much~

**Comment by TheCedarPrince** [comment]
Fully agree with this - right now, you would have two pdfs (one in the main Zotero library and another in your custom directory). Thought it was a bug at first, but I see why this feature is in - however, it would be an incredibly useful and time saving feature to have.

**Comment by jlegewie** [comment]
This issue is unrelated to zotfile.
