### ISSUE TITLE
Release Fx60 version

### ISSUE THREAD

**Issue by dstillman** [jlegewie/zotfile#428]
We're planning to roll out the Firefox 60 and type/field-handling changes to beta within the next day or so, so a new version of ZotFile should be released with the recent changes or else it will be broken for anyone running the Zotero beta. The changes should be backwards-compatible with the current production version of Zotero.

I'm not really familiar with ZotFile, so some quick testing by someone who knows better would be a good idea.

**Comment by jlegewie** [comment]
Looking at this right now and running into one problem right away. Most of the preferences set in `defaults.js` are somehow undefined. For example, `Zotero.Prefs.get("extensions.zotfile.wildcards.default", true)` is undefined but `Zotero.Prefs.get("extensions.zotfile.authors_delimiter", true)` is defined. Many others are undefined as well. Any idea why that is? Thanks!

**Comment by dstillman** [comment]
Are you running an out-of-date dev version? That prefs should be defined in recent versions.

![zotfile-prefs](https://user-images.githubusercontent.com/783082/67163880-6aff0600-f342-11e9-84a8-73108ce136e1.png)

**Comment by jlegewie** [comment]
Yeah, sorry.  :(

**Comment by jlegewie** [comment]
Okay, just made some more fixes and published a new version. Some issues might pop up but thanks for the help!

**Comment by LunarLanding** [comment]
For some reason renaming attachments wasn't working as of the last update. Reinstalling ZotFile fixed it.
