### ISSUE TITLE
Open link to extracted PDF annotation fails on Win10 after upgrading to v.5.0.12

### ISSUE THREAD

**Issue by nmeuschke** [jlegewie/zotfile#432]
First of all, my sincerest thanks for this incredibly useful Zotero addon. I love it and commend you for all the hard work you put into the tool.

After upgrading to the latest version (v.5.0.12) opening the link to an extracted PDF annotation does no longer work on my Win10 machine (Zotero v.5.0.76). 

**I downgraded Zotfile to v.5.0.10 and everything works fine again.**

**Some more details about the error:**
- Extracting the annotations works fine with Zotfile v.5.0.12
- Clicking on "opening the link" does not open the PDF at all
- The error occurs for both stored and linked attachments
- The URLs for the links look fine as far as I can tell, e.g., zotero://open-pdf/library/items/SZFMFDPJ?page=6
- I tried changing the PDF reader setting in both the General Zotero Settings and in the hidden setting extensions.zotfile.pdfExtraction.openPdfWin ... both had no effect
- Setting extensions.zotfile.pdfExtraction.debug to true and enabling Zotero Debug Output Logging yielded no output at all in the Debug Log when clicking on opening link

Please let me know if you require additional information.

**Comment by jlegewie** [comment]
Does it work with the Zotero beta? https://www.zotero.org/support/dev_builds
Make sure you backup your library so that you can easily go back to normal Zotero. Do not install it, if you don't feel comfortable.

**Comment by jlegewie** [comment]
Actually, don't try the beta! Just try Zotfile 5.0.13. Does it fix the problem? The update should happen automatically.

**Comment by qqobb** [comment]
@jlegewie: I had the same issue as in the orignal post, with the same system settings. Updating to Zotfile 5.0.13 solved the issue. Thanks a lot for the quick fix!

Is zotero://open-pdf still handled by Zotfile? If so, removing this and letting Zotero handle these links might have some advantages. I had to use extensions.zotfile.pdfExtraction.openPdfWin some time ago since Zotfile didn't handle Zotero's custom pdf viewer settings.

**Comment by jlegewie** [comment]
zotero://open-pdf is handled by Zotero now. So the zotfile preferences are obsolete, which is the only downside.

**Comment by qqobb** [comment]
Thanks for this info! And thanks a lot for your great add-on!

**Comment by nmeuschke** [comment]
@jlegewie v.5.013 fixed the problem for me, too. Thanks so much for the super quick fix.
