### ISSUE TITLE
[feature request] Automatic renaming of new entries

### ISSUE THREAD

**Issue by kirk86** [jlegewie/zotfile#448]
Please add a checkbox in the `Renaming Rules` tab so that the user can define whether it prefers any newly added item to zotero to be automatically renamed, instead of the current approach which is adding a new item, then locating the new item in the main zotero panel, and right-clicking and selecting manage attachments --> rename attachment.

**Comment by qqobb** [comment]
@kirk86 This works for me with the current version of ZotFile (5.0.14). You can set this in Zotero through "Tools" -> "ZotFile Preferences" -> "Advanced Settings" -> "Other Advanced Settings". BTW, you can also make use of [Zutilo's keyboard shortcuts for Zotfile](https://github.com/willsALMANJ/Zutilo/blob/master/docs/COMMANDS.md#zotfile-functions).

**Comment by kirk86** [comment]
@qqobb Thanks, don't know how I missed that setting in the advanced tab of zotfile, also bonus tip was the zutilo kbd shortcut :smiley:

**Comment by 73** [comment]
I just tried that. It renames the detachment, but not according to my specified `renaming rules`.

**Comment by CodeLoe** [comment]
@qqobb  I have the same problem. The same problem here https://forums.zotero.org/discussion/73142/zotfile-doesnt-automatically-rename-manage-attachments-when-added

**Comment by qqobb** [comment]
@CodeLoe: Please use the Zotero forum for support questions.

For troubleshooting your Zotfile issue, see [this discussion](https://forums.zotero.org/discussion/comment/357133/#Comment_357133) on the Zotero forum.

**Comment by fyemath** [comment]
How to let ZotFile automatically rename the pdf when an item is newly added to Zotero? Before install the ZotFile, Zotero can automatically rename the pdf. However, after the installation of ZotFile, this feature no longer works.

**Comment by ahrendsen** [comment]
Hi @fyemath,

Did you see the reply by qqobb above?

> 
> 
> @kirk86 This works for me with the current version of ZotFile (5.0.14). You can set this in Zotero through "Tools" -> "ZotFile Preferences" -> "Advanced Settings" -> "Other Advanced Settings". BTW, you can also make use of [Zutilo's keyboard shortcuts for Zotfile](https://github.com/willsALMANJ/Zutilo/blob/master/docs/COMMANDS.md#zotfile-functions).

Or are you specifically asking for ZotFile to rename the pdf when an item is added to the in-browser version of Zotero?

@kirk86, If your your issue was addressed, could you close it, please?

Karl

**Comment by fyemath** [comment]
Hi Karl @ahrendsen ,

Thank you! I've already figured that out.

Fei
