### ISSUE TITLE
Set a relative path for custom location of files when  moving new and existing attachments?

### ISSUE THREAD

**Issue by jangkj09** [jlegewie/zotfile#467]
Hi,

I am using zotfile extensively to sync between all my devices. I use the feature so that I can sync copies of the attachment to a custom location (Google Drive folder) so that it is accessible by other pdf readers. The problem is that when I do this move, it is saved with an absolute folder path, so when I try to access the file on another device, it says file not found. This occurs even if the file has been synced on the other system. 
For example:
(On computer 1)
The attachment is moved to : /home/user1/Google\ Drive/zotero/pdfA.pdf

pdfA is synced to computer 2 through Google Drive at: /home/user2/Google\ Drive/zotero/pdfA.pdf

I can open pdfA on computer 2.

If I try to access the file through Zotero on computer 2 I get the message:
'file not found at /home/user1/Google\ Drive/zotero/pdfA.pdf'

I tried specifying a relative path, such as '~/Google\ Drive/zotero' for the location of files, and also creating a symbolic link on computers 1 and 2, so that the path would match, but when I choose this location, it gets expanded to an absolute path, and thus breaks. 

The workaround I have used for now is to go directly to the google drive folder and open the pdf there when working on computer 2, which is rather inconvenient when having to sift through multiple subfolders and collections.

I do know there is a send to tablet feature and that also works for now, but I'd rather just be able to sync the pdf with the corresponding annotations without having to go through that trouble.

Is there some way to set the location as a relative path and not an absolute path?

Thanks.

**Comment by qqobb** [comment]
Please use the Zotero forum for support questions.

Zotero's documentation might be helpful:
-  [Stored Files and Linked Files](https://www.zotero.org/support/attaching_files#stored_files_and_linked_files)
- For linked files, you can use relative paths by setting up a [Linked Attachment Base Directory](https://www.zotero.org/support/preferences/advanced#files_and_folders).
- For questions related to syncing see here: https://www.zotero.org/support/sync.

**Comment by jangkj09** [comment]
Thanks, this information resolved my problem. I didn't realize it was a setting for zotero.
