### ISSUE TITLE
Firefox extension no longer available?

### ISSUE THREAD

**Issue by juanortizfreuler** [jlegewie/zotfile#498]
Seems like there is no longer a Firefox extension?

i.e. URL shared on the main site and readme file is no longer available ->  https://addons.mozilla.org/en-US/firefox/addon/zotfile/

Or for the standalone: https://addons.mozilla.org/firefox/downloads/file/585224/zotfile-4.2.8-fx.xpi?src=dp-btn-primary

Basic search does not offer it among the results -> https://addons.mozilla.org/en-US/firefox/search/?platform=mac&q=zotfile

Or even broader searches-> https://addons.mozilla.org/en-US/firefox/search/?platform=mac&q=zotero

Is this a momentarily glitch or will Zotfile no longer be supported on Firefox?

Thanks!

**Comment by bwiernik** [comment]
Zotero hasn't been a Firefox extension--only a standalone program--for many years. Zotfile is an extension for Zotero, not Firefox, so there is no need to distribute it via Mozilla (it also uses technologies that Mozilla no longer supports).

**Comment by juanortizfreuler** [comment]
Thanks! For some reason, when downloading the Zotfile extension on Firefox, Firefox seems to try to install the extension onto the browser and creates a fail message, which made me think there was a problem in there. There are also several references to the different browsers in the Readme file, which made me think there was a problem with the firefox integration.

 In any case, after seeing your message I managed to install the Zotfile plugin through Zotero and it works perfectly. Thanks for your response and I hope this is useful to others!!

**Comment by ahrendsen** [comment]
Hi @juanortizfreuler,

If your question has been answered, please close the issue. 

Thanks,
Karl

**Comment by juanortizfreuler** [comment]
Thanks for the reminder. Issue closed. See above.
