### ISSUE TITLE
Firefox could not add Zotfile extension by manually installing from the file - File corrupt error

### ISSUE THREAD

**Issue by gautham949** [jlegewie/zotfile#499]
I downloaded the .xpi file following the instructions and tried to install it from the Install add-on from the file. 

Firefox could not add the Zotfile extension from the file. 

Shows the error that the file appears to be corrupt.

**Comment by manuelhubacher** [comment]
This could be a duplicate of #398. As @adam3smith mentioned there, ZotFile is a Zotero add-on, not a Firefox add-on.

**Comment by gautham949** [comment]
That's right. I did exactly that, "Download the .xpi file (right-click --> save link as in Firefox, e.g.) and then install it from the Tools--> add-ons menu in Zotero." 

It showed the same error that the file appears to be corrupt.

**Comment by adam3smith** [comment]
Which Zotero version? The file is fine unless, of course, something went wrong during the download process.

**Comment by gautham949** [comment]
I downloaded Zotero 5.0.93. I downloaded it multiple times and tried installing.  

Operating System; Linux Mint 20 Ulyana

**Comment by adam3smith** [comment]
And that's the standard Zotero install from zotero.org/download or are you using a package like the .deb or the flatpack?
Could we get a screenshot of the error message?

**Comment by gautham949** [comment]
I downloaded it from zotero.org/download. Here's the picture showing the error. 
![IMG_20201216_110424](https://user-images.githubusercontent.com/31089576/102309392-acaf2f00-3f8e-11eb-9b3f-c8dec1495e72.jpg)

**Comment by manuelhubacher** [comment]
It looks like you try to install the plugin to Firefox and not to Zotero. As mentioned in the install instructions, you have to start Zotero 5 and go to "Tool -> Add-ons -> Tools for all Add-ons (the small, drop-down wheel in the top right corner) -> Install Add-on From File" and select the downloaded .xpi file. 

<img width="1242" alt="Bildschirmfoto 2020-12-16 um 09 26 38" src="https://user-images.githubusercontent.com/17408325/102324743-8a171900-3f82-11eb-960c-d6c7cfc0e1e3.png">

<img width="390" alt="Bildschirmfoto 2020-12-16 um 09 26 41" src="https://user-images.githubusercontent.com/17408325/102324772-93a08100-3f82-11eb-8f4c-e7d1d10a2f70.png">

**Comment by gautham949** [comment]
Oh, damn! I'm such a fool. It worked.

Thanks a lot for your assistance.
