### ISSUE TITLE
rename pdfs according to their citekeys

### ISSUE THREAD

**Issue by tjallemaal** [jlegewie/zotfile#504]
ok i still have no idea how to make zotero rename my pdf's according to their corresponding citekeys. 
this freaks me out. it just cant be so hard. 
can anybody give me a proper recipe or documentation?! 
i want zotero to rename my pdfs automatically as well. 
T-T

ps: i have zotero 5 installed

**Comment by greenmeen** [comment]
Are you using Better BibTeX ?
If so, the latest Zotfile version (**v5.0.16**) gives you access to a wildcard for using the Better BibTeX citekey.

To use it, set `{%b}` as format in Zotero Preferences > Renaming Rules. It'll name the attachment with the citekey (without initial @).

**Comment by ahrendsen** [comment]
Hi @tjallemaal,

Keep in mind this is an issues page for ZotFile, and extension of Zotero. ZotFile can rename your files for you and put them all in a (single) folder of your choice. 

The documentation for installing ZotFile (http://zotfile.com/#how-to-install--set-up-zotfile) describes how to set up ZotFile with your Zotero installation. Once you have ZotFile, investigate the options (Tools > ZotFile Preferences...) to ensure the files will be renamed as you desire. Then, you can rename existing files in your library by right click and selecting the appropriate options, as shown in the attached image.
![ZotFileRename](https://user-images.githubusercontent.com/6043860/108234161-263bd880-710a-11eb-9bcd-1a04d48a8204.png)


If you're still having difficulty, please provide more details about the steps you are taking to rename the files.

Karl
