### ISSUE TITLE
[Suggestion] When renaming attachment file name, add ignore field. 

### ISSUE THREAD

**Issue by northword** [jlegewie/zotfile#507]
![image](https://user-images.githubusercontent.com/44738481/106017206-30664a80-60fb-11eb-8b8d-4fb15bc83584.png)

Sometimes for subscripts and subscripts, `<sub>` is added to the title. At this time, `sub` will also be added to the attachment file name. 

I hope to set an ignore field. Or replace the specified characters with other characters, such as `<sub>` in this example,  replace with `_`, and `</sub>` replace with `` . 

For example: 

```
# ignore
Han Lupeng et al_2019_Selective Catalytic Reduction of NOx with NH3 by Using Novel Catalysts: State of the Art and Future Prospects.pdf

# replace
Han Lupeng et al_2019_Selective Catalytic Reduction of NO_x with NH_3 by Using Novel Catalysts: State of the Art and Future Prospects.pdf
```

**Comment by qqobb** [comment]
This is already possible, but not straightforward. You have to use user-defined wildcards, see https://github.com/jlegewie/zotfile/issues/455.

**Comment by northword** [comment]
> This is already possible, but not straightforward. You have to use user-defined wildcards, see #455.

This is effective, thanks!
