### ISSUE TITLE
Include support for renaming EPUBs

### ISSUE THREAD

**Issue by jzeneto** [jlegewie/zotfile#517]
Hi! I have one simple problem: Zotfile refuses to rename EPUBs (`*.epub`), which is unexpected, as EPUBs are similar to PDFs (or even DOCX, which is supported) in the sense of being an entire document within one file.

Please, is it possible to add support for renaming EPUBs with Zotfile?

Currently I'm using Zotfile to keep my attachments away from Zotero database, in a folder sync'ed with Google Drive. Storing EPUBs in that folder would be logical.

(I know of #47, which is a more robust and complex solution. What I mean here is a slightly different and much simpler problem.)

Thanks in advance!

**Comment by astroHaoPeng** [comment]
Did you check "Zotero preference -- Advanced Settings -- Other advanced settings -- Only work with the following filetypes"? Try adding `.epub`.

Provide a testing epub file in your reply if it still doesn't file, cause it may be the problem of a broken file.

**Comment by jzeneto** [comment]
@astroHaoPeng **It works!** Just a little correction: it's not a Zotero preference, but a Zotfile preference instead: in Zotero, go to `Tools` > `ZotFile Preferences` > `Advanced Settings` and so on, as you cited.

I'd like to suggest to @jlegewie to include `epub` in that preference by default, just as `djvu` is already included.
