### ISSUE TITLE
Add article from PDF

### ISSUE THREAD

**Issue by raffaem** [jlegewie/zotfile#533]
It happens that I download PDF from the web.

When I download a PDF from the web, my workflow to import it into Zotero is as follows:

1. Create an empty article
2. Right click and "Attach new file"
3. Move the attached file out of the article
4. Remove the article
5. Right click on the PDF file and generate metadata from it
6. Right click on the attachment and rename it based on parent's metadata

Is there a shorter way of doing this?

**Comment by ahrendsen** [comment]
YES. 

This seems to be a question that isn't directly related to ZotFile, but a general question about Zotero, so I would recommend closing the issue. 

In fact, based on your workflow, it doesn't even sound like you're using ZotFile. Given you posted this 27 days ago, I'm hopeful you've found a solution already. If you haven't feel free to send me a direct message and I can help you out.

Karl

**Comment by raffaem** [comment]
Yes I'm using Zotfile definitely.

I discovered I can move the file from the file manager into Zotero. Then it gets added and after sometime it gets metadata and build an article entry (not sure if the metadata are extracted from the PDF or get from the internet).

I think we could have a File->Add PDF kind of thing

**Comment by ahrendsen** [comment]
Yeah, I don't know the details of how Zotero works, but I've always assumed that the behavior you describe is done through the PDF metadata. In situations where the PDF metadata isn't available, maybe what I write below will be helpful.

First, I would recommend using the Zotero Firefox extension. When you find an article online, you can press the "Save to Zotero" button and it will get all the metadata for the paper from the website and most often will be able to download the PDF as well. If ZotFile is configured correctly, it will automatically move the file to your desired location and rename it for you.

When the PDF doesn't download automatically, you can download it manually and then use ZotFile's "Attach New File" right click option to get the file linked up.

Another option is the "Magic Wand" button in Zotero where you add items by ISBN or DOI. Simply copy and paste the relevant info into the box that appears when you click the magic wand and Zotero will do its best to get the relevant metadata from the internet. 

The "File -> Add PDF"-like behavior is found by pressing the green "+" button, then selecting "Link to File..."
