### ISSUE TITLE
Remove confirmation dialog when attaching new file

### ISSUE THREAD

**Issue by MavropaliasG** [jlegewie/zotfile#536]
Hello,
Thank you for this amazing extension
When left-clicking an item and selecting 'Attach new file', a faster behavior would be to simply do that, without asking for confirmation afterward. I need to do this at least 30 times a day, so it would be helpful to not have to do an additional action (or at least include a 'don't ask again' option?).

Thank you

**Comment by ahrendsen** [comment]
Hi there,

Try "Tools > Zotfile Preferences > Advanced Settings > Ask user when attaching new files"

I'm fairly confident this is the solution you're looking for, so please close the issue if this resolves your problem.

Karl

**Comment by MavropaliasG** [comment]
Thank you!
