### ISSUE TITLE
“Zotfile is incompatible with Zotero 6.0”

### ISSUE THREAD

**Issue by Leonardo-Hu** [jlegewie/zotfile#590]
Sorry to bother you. But "Zotfile is incompatible with Zotero 6.0". Can you do something with it, please?

**Comment by Zhijia-urbanex** [comment]
Same problem here!

**Comment by yeony014** [comment]
> 抱歉打扰你。但是“Zotfile 与 Zotero 6.0 不兼容”。你能用它做点什么吗？

i can't get Extraction of PDF Annotations

**Comment by zpdg** [comment]
Same problem here! These is "Extract Annotations" when I launch zotero, but disappears a few seconds later. I repeated several times.

**Comment by llxlr** [comment]
#589

**Comment by SunRhine** [comment]
I can't get Extraction of PDF Annotations，either！

**Comment by jlegewie** [comment]
Zotero 6 can now extract annotations directly. No need to use zottle for that. Here is the Zotero 6 announcement with details: https://www.zotero.org/blog/zotero-6/
