### ISSUE TITLE
Extraction of PDF Annotations feature disappear

### ISSUE THREAD

**Issue by SunRhine** [jlegewie/zotfile#592]
zotfile version：5.1.0 
zotero ver：6.0.1
windows 11
In the "manage attachments" menu, the option to extract pdf comments is not found!!!

**Comment by jlegewie** [comment]
Zotero 6 can now extract annotations directly. No need to use zottle for that. Here is the Zotero 6 announcement with details: https://www.zotero.org/blog/zotero-6/

**Comment by egumasa** [comment]
Would you be able to keep the extraction option through Zotfile? The native Zotero does not extract URI to the original paper, which is a very useful feature of Zotfile or zottle (as you hinted?).

**Comment by jlegewie** [comment]
Zotero extraction actually does. Just click on the extracted text and then "Show on page". Ask in the zotero forum if you have problems with that.
