### ISSUE TITLE
`Manage Attachments --> Extract Annotations` changed to `Add Note from Annotations` in Zotero v6 update

### ISSUE THREAD

**Issue by sgbaird** [jlegewie/zotfile#596]
Since it took me more than a few minutes to figure this out, figured it was worth putting a memo here. Feel free to close whenever.

6th option down in the following image:

![image](https://user-images.githubusercontent.com/45469701/159844975-ca39a829-50a2-4632-a7ce-38937d72effa.png)

**Comment by viertel97** [comment]
Hey, but that is the functionality implemented by Zotero 6 (as mentioned [here](https://www.zotero.org/support/kb/zotfile_extract_annotations)) instead of the (in my opinion, more advanced) functionality of Zotfile, isn't it?

**Comment by jlegewie** [comment]
Yes, that is the extraction function implemented in Zotero 6.0. It replaces zotfile’s and should be much better.
