### ISSUE TITLE
Don't add unnecessary numbers on repeated rename

### ISSUE THREAD

**Issue by cpence** [jlegewie/zotfile#91]
If you're maintaining a linked files directory, and you run "Rename attachments", then immediately run "Rename attachments" again, ZotFile will add a "2" (or a "3", etc.) to the end of the filename, because it detects a collision between the file's *current* name and its "new" name.  It'd be great if ZotFile saw that this wasn't really a rename and left things alone without adding extra 2s and 3s to all your filenames.

(You might, for example, want to do a "Select all" -> "Rename attachments" if you changed the ZotFile naming pattern.  If that resulted in *any* file collisions, though, then you'd get unnecessary numbers on some of your filenames.  I've been trying to do that today, and running into this problem.)

**Comment by jlegewie** [comment]
I think this is fixed. Please report if not.

**Comment by cpence** [comment]
Yes, I haven't seen this bug in a couple of versions. (Forgot this issue was open, or I would have come to comment myself!) Thanks!
